**Подготовка файла 2100.csv на основе данных сводных файлов 2016-2018 годов**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

- `..\Data\{год}\` - папка для хранения созданнного 2100.csv для определенного года
- `..\Data\{год}\Original` - папка для хранения оригинального файла xlsx
- `..\Data\Common\` - папка для хранения итогового результата 2100.csv сводный

Пример: 
- *E:/IrkutskProject/Data/2016/Original/ф33  правл за 2016г Иркутская обл.xlsx*
- *E:/IrkutskProject/Data/2016/2100.csv*

In [4]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [5]:
# Установка библиотеки для чтения excel. 
# !pip install openpyxl
# !pip install xlrd

1) Подкотовка датасетов формы 2200 за 2016-2018 года

In [7]:
# Список годов для обработки
#years = [2016, 2017, 2018]

# Название оригинального файла
#original_names = {
#    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
#    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
#    2018: 'ф.33 и ф.8  Иркутская область  2018.xls'
#}

years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

# Название оригинального файла
original_names = {
    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
    2018: 'ф.33 и ф.8  Иркутская область  2018.xls',
    2019: 'Свод ф.33 ,ф.8 область правильный 03.02. 2019.xls',
    2020: 'Свод ф.33,8  Иркутская область 2020 верный.xls',
    2021: 'свод область 2021  верный .xls',
    2022: 'свод верн Иркутская область 2022г  ф.33, 8.xls',
    2023: 'свод  Иркутская область верн 2023г..xls',
    2024: 'свод область 2024г.ф.33,8 верн Иркутская обл.xls'
}
original_url = {}
path = 'E:/IrkutskProject/Data/'

df_2100 = {}

for year in years:
    original_path = f'{path}{year}/Original/'
    original_url[year] = original_path + original_names[year]
    
    if year == 2016:
        df = pd.read_excel(original_url[year], engine='openpyxl', sheet_name = '2100,2110,2120')

        # Отфильтруем таблицу 2100
        df_2100[year] = df.iloc[3:26]    

    else:
        df = pd.read_excel(original_url[year], engine='xlrd', sheet_name = '2100')
        
        df_2100[year] = df.iloc[1:18]
        
    # Удаляем пустые столбцы
    df_2100[year] = df_2100[year].dropna(how='all', axis=1)

    # Удаляем пустые строки
    df_2100[year] = df_2100[year].dropna(how='all')
        
    #df_2100[year] = df_2100[year].drop(df_2100[year].columns[1:2], axis=1)
    #df_2100[year].drop(df_2100[year].index[3:4], inplace=True)
    df_2100[year] = df_2100[year].iloc[:, :9]

    df_2100[year] = df_2100[year].reset_index(drop=True)
    
    # Названия столбцов
    df_2100[year].columns = [0, 1, 2, 3, 4, 5, 6, 7, 8]

    # Подписываем строки в соответствии с шаблоном
    df_2100[year].iloc[0, 0] = 'Формы туберкулеза'
    df_2100[year].iloc[0, 2] = 'Код по МКБ-Х пересмотра'
    df_2100[year].iloc[0, 3] = 'Взято на учет в отчетном году больных с первые в жизни установленным диагнозом'
    df_2100[year].iloc[0, 6] = 'Контингенты больных на конец отчетного года'
    
    df_2100[year].iloc[4, 0] = 'Туберкулез органов дыхания - всего'
    df_2100[year].iloc[5, 0] = 'Туберкулез органов дыхания - в том числе туберкулез легких'
    df_2100[year].iloc[6, 0] = 'Туберкулез органов дыхания - из него: фиброзно-кавернозный'
    df_2100[year].iloc[7, 0] = 'Из общего числа больных туберкулезом легких выявлено в фазе распада'
    df_2100[year].iloc[8, 0] = 'Из общего числа больных туберкулезом легких выявлено без распада и без бактериовыделения'
    df_2100[year].iloc[9, 0] = 'Другие локализации туберкулеза'
    df_2100[year].iloc[10, 0] = 'Итого (сумма строк 01, 06)'
    df_2100[year].iloc[11, 0] = 'Имеют инвалидность в связи с туберкулезом'
    df_2100[year].iloc[12, 0] = 'Имеют инвалидность в связи с туберкулезом в том числе первой группы'
    df_2100[year].iloc[13, 0] = 'Имеют инвалидность в связи с туберкулезом в том числе второй группы'
    df_2100[year].iloc[14, 0] = 'Обследовано на АТ к ВИЧ'
    df_2100[year].iloc[15, 0] = 'Обследовано на АТ к ВИЧ из них с положительным результатом методом иммунного блотинга'
    df_2100[year].iloc[16, 0] = 'Туберкулез в сочетании с ВИЧ'

    df_2100[year].iloc[2, 3] = 'всего'
    df_2100[year].iloc[2, 6] = 'всего'

    df_2100[year].iloc[2, 4] = 'из них детей от 0 до 14 лет'
    df_2100[year].iloc[2, 7] = 'из них детей от 0 до 14 лет'

    df_2100[year].iloc[2, 5] = 'из них подростков 15-17 лет'
    df_2100[year].iloc[2, 8] = 'из них подростков 15-17 лет'

    for j in range(1, 10):
        df_2100[year].iloc[3, j - 1] = j

    for i in range(1, 14):
        df_2100[year].iloc[i + 3, 1] = i

    # Выкладываем подготовленные данные в файл
    df_2100[year].to_csv(f'E:/IrkutskProject/Data/{year}/2100.csv', index=False)

In [8]:
df_2100[2016]

,0,1,2,3,4,5,6,7,8
0,Формы туберкулеза,№ стр.,Код по МКБ-Х пересмотра,Взято на учет в отчетном году больных с первые...,NaN,NaN,Контингенты больных на конец отчетного года,NaN,NaN
1,NaN,NaN,NaN,всего,в том числе,NaN,всего,в том числе,NaN
2,NaN,NaN,NaN,всего,из них детей от 0 до 14 лет,из них подростков 15-17 лет,всего,из них детей от 0 до 14 лет,из них подростков 15-17 лет
3,1,2,3,4,5,6,7,8,9
4,Туберкулез органов дыхания - всего,1,A15;A16;A19 часть,2293,89,31,5751,110,33
5,Туберкулез органов дыхания - в том числе тубер...,2,A15.0-A15.3; A15.7 часть;A16.0-A16.2;A16.7 час...,2171,41,29,5574,49,31
6,Туберкулез органов дыхания - из него: фиброзно...,3,A15.0-A15.3; A16.0-A16.2,16,NaN,NaN,957,NaN,NaN
7,Из общего числа больных туберкулезом легких вы...,4,NaN,929,1,13,2780,1,10
8,Из общего числа больных туберкулезом легких вы...,5,NaN,968,40,14,2018,47,21
9,Другие локализации туберкулеза,6,A17;A18;A19 часть,110,6,2,569,11,3
10,"Итого (сумма строк 01, 06)",7,NaN,2403,95,33,6320,121,36
11,Имеют инвалидность в связи с туберкулезом,8,NaN,461,4,NaN,2365,7,1
12,Имеют инвалидность в связи с туберкулезом в то...,9,NaN,11,NaN,NaN,49,NaN,NaN
13,Имеют инвалидность в связи с туберкулезом в то...,10,NaN,237,NaN,NaN,1242,2,NaN
14,Обследовано на АТ к ВИЧ,11,NaN,2386,95,31,6307,121,34
15,Обследовано на АТ к ВИЧ из них с положительным...,12,NaN,803,2,NaN,2215,5,1
16,Туберкулез в сочетании с ВИЧ,13,A15-A19 и B20.0-23.0; Z 21,803,2,NaN,2215,5,1

In [9]:
#df_2100[2024]

2) Подготовка сводного датасета 2100.csv

In [11]:
columns = [
    'Формы туберкулеза',
    'Уточнение',
    'Еще уточнение',
    'Код по МКБ-Х пересмотра',
    'Год',
    'Значение',
    'Строка',
    'Графа',
    'Таблица'
]

data = []
data_2016_2018 = []

df_2100_long = pd.DataFrame(columns=columns)
df_2100_long_2016_2018 = pd.DataFrame(columns=columns)

for year in years:
    for row_number in range(4, df_2100[year].shape[0]):
        for col_number in range(3, 6):
            new_row = []
            new_row.append(df_2100[year].iloc[row_number, 0]) # Загловок
            new_row.append(df_2100[year].iloc[0, 3]) # Уточнение
            new_row.append(df_2100[year].iloc[2, col_number]) # Еще уточнение
            new_row.append(df_2100[year].iloc[row_number, 2] if pd.notnull(df_2100[year].iloc[row_number, 2]) else np.nan) # Код МКБ
            new_row.append(year) # Год
            #new_row.append(df_2100[year].iloc[row_number, col_number] if pd.notnull(df_2100[year].iloc[row_number, col_number]) else 0) # Значение

            new_row.append(df_2100[year].iloc[row_number, col_number] if (
                (df_2100[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2100[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            
            new_row.append(df_2100[year].iloc[row_number, 1]) # Строка
            new_row.append(df_2100[year].iloc[3, col_number]) # Графа
            new_row.append(2100) # Таблица)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)

        for col_number in range(6, 9):
            new_row = []
            new_row.append(df_2100[year].iloc[row_number, 0]) 
            new_row.append(df_2100[year].iloc[0, 6])
            new_row.append(df_2100[year].iloc[2, col_number])
            new_row.append(df_2100[year].iloc[row_number, 2] if pd.notnull(df_2100[year].iloc[row_number, 2]) else np.nan)
            new_row.append(year)
            #new_row.append(df_2100[year].iloc[row_number, col_number] if pd.notnull(df_2100[year].iloc[row_number, col_number]) else 0)

            new_row.append(df_2100[year].iloc[row_number, col_number] if (
                (df_2100[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2100[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            
            new_row.append(df_2100[year].iloc[row_number, 1]) # Строка
            new_row.append(df_2100[year].iloc[3, col_number]) # Графа
            new_row.append(2100) # Таблица
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)

df_2100_long = pd.DataFrame(data, columns=columns)
df_2100_long_2016_2018 = pd.DataFrame(data_2016_2018, columns=columns)

display(df_2100_long)

,Формы туберкулеза,Уточнение,Еще уточнение,Код по МКБ-Х пересмотра,Год,Значение,Строка,Графа,Таблица
0,Туберкулез органов дыхания - всего,Взято на учет в отчетном году больных с первые...,всего,A15;A16;A19 часть,2016,2293.0,1,4,2100
1,Туберкулез органов дыхания - всего,Взято на учет в отчетном году больных с первые...,из них детей от 0 до 14 лет,A15;A16;A19 часть,2016,89.0,1,5,2100
2,Туберкулез органов дыхания - всего,Взято на учет в отчетном году больных с первые...,из них подростков 15-17 лет,A15;A16;A19 часть,2016,31.0,1,6,2100
3,Туберкулез органов дыхания - всего,Контингенты больных на конец отчетного года,всего,A15;A16;A19 часть,2016,5751.0,1,7,2100
4,Туберкулез органов дыхания - всего,Контингенты больных на конец отчетного года,из них детей от 0 до 14 лет,A15;A16;A19 часть,2016,110.0,1,8,2100
...,...,...,...,...,...,...,...,...,...
697,Туберкулез в сочетании с ВИЧ,Взято на учет в отчетном году больных с первые...,из них детей от 0 до 14 лет,А15-А19 и В20.0 – 23.0; Z 21,2024,0.0,13,5,2100
698,Туберкулез в сочетании с ВИЧ,Взято на учет в отчетном году больных с первые...,из них подростков 15-17 лет,А15-А19 и В20.0 – 23.0; Z 21,2024,1.0,13,6,2100
699,Туберкулез в сочетании с ВИЧ,Контингенты больных на конец отчетного года,всего,А15-А19 и В20.0 – 23.0; Z 21,2024,0.0,13,7,2100
700,Туберкулез в сочетании с ВИЧ,Контингенты больных на конец отчетного года,из них детей от 0 до 14 лет,А15-А19 и В20.0 – 23.0; Z 21,2024,0.0,13,8,2100
701,Туберкулез в сочетании с ВИЧ,Контингенты больных на конец отчетного года,из них подростков 15-17 лет,А15-А19 и В20.0 – 23.0; Z 21,2024,0.0,13,9,2100

In [12]:
df_2100_long_2016_2018.to_csv(f'{path}Common_2016-2018/2100_2016-2018.csv', index=False)
df_2100_long.to_csv(f'{path}Common/2100_2016-2024.csv', index=False)