**Подготовка файла 2100.csv на основе данных сводных файлов 2016-2018 годов**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

- `..\Data\{год}\` - папка для хранения созданнного 2100.csv для определенного года
- `..\Data\{год}\Original` - папка для хранения оригинального файла xlsx
- `..\Data\Common\` - папка для хранения итогового результата 2100.csv сводный

Пример: 
- *E:/IrkutskProject/Data/2016/Original/ф33  правл за 2016г Иркутская обл.xlsx*
- *E:/IrkutskProject/Data/2016/2100.csv*

In [4]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [5]:
# Установка библиотеки для чтения excel. 
# !pip install openpyxl
# !pip install xlrd

1) Подкотовка датасетов формы 2200 за 2016-2018 года

In [7]:
# Список годов для обработки
years = [2016, 2017, 2018]

# Название оригинального файла
original_names = {
    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
    2018: 'ф.33 и ф.8  Иркутская область  2018.xls'
}
original_url = {}
path = 'E:/IrkutskProject/Data/'

df_2100 = {}

for year in years:
    original_path = f'{path}{year}/Original/'
    original_url[year] = original_path + original_names[year]
    
    if year == 2016:
        df = pd.read_excel(original_url[year], engine='openpyxl', sheet_name = '2100,2110,2120')

        # Отфильтруем таблицу 2100
        df_2100[year] = df.iloc[3:26]    

    else:
        df = pd.read_excel(original_url[year], engine='xlrd', sheet_name = '2100')
        
        df_2100[year] = df.iloc[1:18]
        
    # Удаляем пустые столбцы
    df_2100[year] = df_2100[year].dropna(how='all', axis=1)

    # Удаляем пустые строки
    df_2100[year] = df_2100[year].dropna(how='all')
        
    df_2100[year] = df_2100[year].drop(df_2100[year].columns[1:2], axis=1)
    df_2100[year].drop(df_2100[year].index[3:4], inplace=True)
    df_2100[year] = df_2100[year].iloc[:, :8]

    df_2100[year] = df_2100[year].reset_index(drop=True)
    
    # Названия столбцов
    df_2100[year].columns = [0, 1, 2, 3, 4, 5, 6, 7]

    # Подписываем строки в соответствии с шаблоном
    df_2100[year].iloc[0, 0] = 'Формы туберкулеза'
    df_2100[year].iloc[0, 1] = 'Код по МКБ-Х пересмотра'
    df_2100[year].iloc[0, 2] = 'Взято на учет в отчетном году больных с первые в жизни установленным диагнозом'
    df_2100[year].iloc[0, 5] = 'Контингенты больных на конец отчетного года'
    
    df_2100[year].iloc[3, 0] = 'Туберкулез органов дыхания - всего'
    df_2100[year].iloc[4, 0] = 'Туберкулез органов дыхания - в том числе туберкулез легких'
    df_2100[year].iloc[5, 0] = 'Туберкулез органов дыхания - из него: фиброзно-кавернозный'
    df_2100[year].iloc[6, 0] = 'Из общего числа больных туберкулезом легких выявлено в фазе распада'
    df_2100[year].iloc[7, 0] = 'Из общего числа больных туберкулезом легких выявлено без распада и без бактериовыделения'
    df_2100[year].iloc[8, 0] = 'Другие локализации туберкулеза'
    df_2100[year].iloc[9, 0] = 'Итого (сумма строк 01, 06)'
    df_2100[year].iloc[10, 0] = 'Имеют инвалидность в связи с туберкулезом'
    df_2100[year].iloc[11, 0] = 'Имеют инвалидность в связи с туберкулезом в том числе первой группы'
    df_2100[year].iloc[12, 0] = 'Имеют инвалидность в связи с туберкулезом в том числе второй группы'
    df_2100[year].iloc[13, 0] = 'Обследовано на АТ к ВИЧ'
    df_2100[year].iloc[14, 0] = 'Обследовано на АТ к ВИЧ из них с положительным результатом методом иммунного блотинга'
    df_2100[year].iloc[15, 0] = 'Туберкулез в сочетании с ВИЧ'

    df_2100[year].iloc[2, 2] = 'всего'
    df_2100[year].iloc[2, 5] = 'всего'

    df_2100[year].iloc[2, 3] = 'из них детей от 0 до 14 лет'
    df_2100[year].iloc[2, 6] = 'из них детей от 0 до 14 лет'

    df_2100[year].iloc[2, 4] = 'из них подростков 15-17 лет'
    df_2100[year].iloc[2, 7] = 'из них подростков 15-17 лет'

    # Выкладываем подготовленные данные в файл
    df_2100[year].to_csv(f'E:/IrkutskProject/Data/{year}/2100.csv')

In [8]:
df_2100[2016].head()

,0,1,2,3,4,5,6,7
0,Формы туберкулеза,Код по МКБ-Х пересмотра,Взято на учет в отчетном году больных с первые...,NaN,NaN,Контингенты больных на конец отчетного года,NaN,NaN
1,NaN,NaN,всего,в том числе,NaN,всего,в том числе,NaN
2,NaN,NaN,всего,из них детей от 0 до 14 лет,из них подростков 15-17 лет,всего,из них детей от 0 до 14 лет,из них подростков 15-17 лет
3,Туберкулез органов дыхания - всего,A15;A16;A19 часть,2293,89,31,5751,110,33
4,Туберкулез органов дыхания - в том числе тубер...,A15.0-A15.3; A15.7 часть;A16.0-A16.2;A16.7 час...,2171,41,29,5574,49,31

2) Подготовка сводного датасета 2100.csv

In [10]:
columns = [
    'Формы туберкулеза',
    'Уточнение',
    'Еще уточнение',
    'Код по МКБ-Х пересмотра',
    'Год',
    'Значение'
]

data = []

df_2100_long = pd.DataFrame(columns=columns)

for year in years:
    for row_number in range(3, df_2100[year].shape[0]):
        for col_number in range(2, 5):
            new_row = []
            new_row.append(df_2100[year].iloc[row_number, 0]) 
            new_row.append(df_2100[year].iloc[0, 2])
            new_row.append(df_2100[year].iloc[2, col_number])
            new_row.append(df_2100[year].iloc[row_number, 1] if pd.notnull(df_2100[year].iloc[row_number, 1]) else np.nan)
            new_row.append(year)
            new_row.append(df_2100[year].iloc[row_number, col_number] if pd.notnull(df_2100[year].iloc[row_number, col_number]) else 0)
            data.append(new_row)

        for col_number in range(5, 8):
            new_row = []
            new_row.append(df_2100[year].iloc[row_number, 0]) 
            new_row.append(df_2100[year].iloc[0, 5])
            new_row.append(df_2100[year].iloc[2, col_number])
            new_row.append(df_2100[year].iloc[row_number, 1] if pd.notnull(df_2100[year].iloc[row_number, 1]) else np.nan)
            new_row.append(year)
            new_row.append(df_2100[year].iloc[row_number, col_number] if pd.notnull(df_2100[year].iloc[row_number, col_number]) else 0)
            data.append(new_row)            

df_2100_long = pd.DataFrame(data, columns=columns)

display(df_2100_long)

,Формы туберкулеза,Уточнение,Еще уточнение,Код по МКБ-Х пересмотра,Год,Значение
0,Туберкулез органов дыхания - всего,Взято на учет в отчетном году больных с первые...,всего,A15;A16;A19 часть,2016,2293
1,Туберкулез органов дыхания - всего,Взято на учет в отчетном году больных с первые...,из них детей от 0 до 14 лет,A15;A16;A19 часть,2016,89
2,Туберкулез органов дыхания - всего,Взято на учет в отчетном году больных с первые...,из них подростков 15-17 лет,A15;A16;A19 часть,2016,31
3,Туберкулез органов дыхания - всего,Контингенты больных на конец отчетного года,всего,A15;A16;A19 часть,2016,5751
4,Туберкулез органов дыхания - всего,Контингенты больных на конец отчетного года,из них детей от 0 до 14 лет,A15;A16;A19 часть,2016,110
...,...,...,...,...,...,...
229,Туберкулез в сочетании с ВИЧ,Взято на учет в отчетном году больных с первые...,из них детей от 0 до 14 лет,А15-А19 и В20.0 – 23.0; Z 21,2018,7
230,Туберкулез в сочетании с ВИЧ,Взято на учет в отчетном году больных с первые...,из них подростков 15-17 лет,А15-А19 и В20.0 – 23.0; Z 21,2018,2
231,Туберкулез в сочетании с ВИЧ,Контингенты больных на конец отчетного года,всего,А15-А19 и В20.0 – 23.0; Z 21,2018,1472
232,Туберкулез в сочетании с ВИЧ,Контингенты больных на конец отчетного года,из них детей от 0 до 14 лет,А15-А19 и В20.0 – 23.0; Z 21,2018,15
233,Туберкулез в сочетании с ВИЧ,Контингенты больных на конец отчетного года,из них подростков 15-17 лет,А15-А19 и В20.0 – 23.0; Z 21,2018,2

In [11]:
df_2100_long.to_csv(f'{path}Common/2100_2016-2018.csv', index=False)