**Подготовка файла 2200.csv на основе данных сводных файлов 2016-2018 годов**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

- `..\Data\{год}\` - папка для хранения созданнного 2200.csv для определенного года
- `..\Data\{год}\Original` - папка для хранения оригинального файла xlsx
- `..\Data\Common\` - папка для хранения итогового результата 2200.csv сводный

Пример: 
- *E:/IrkutskProject/Data/2016/Original/ф33  правл за 2016г Иркутская обл.xlsx*
- *E:/IrkutskProject/Data/2016/2200.csv*

In [4]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [5]:
# Установка библиотеки для чтения excel. 
!pip install openpyxl
!pip install xlrd

Requirement already satisfied: openpyxl in c:\users\lenovo\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\lenovo\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: xlrd in c:\users\lenovo\anaconda3\lib\site-packages (2.0.2)

In [6]:
# Проверка версии
# pip show openpyxl

1) Подкотовка датасетов формы 2200 за 2016-2018 года

In [8]:
# Список годов для обработки
#years = [2016, 2017, 2018]

# Название оригинального файла
#original_names = {
#    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
#    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
#    2018: 'ф.33 и ф.8  Иркутская область  2018.xls'
#}

years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

# Название оригинального файла
original_names = {
    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
    2018: 'ф.33 и ф.8  Иркутская область  2018.xls',
    2019: 'Свод ф.33 ,ф.8 область правильный 03.02. 2019.xls',
    2020: 'Свод ф.33,8  Иркутская область 2020 верный.xls',
    2021: 'свод область 2021  верный .xls',
    2022: 'свод верн Иркутская область 2022г  ф.33, 8.xls',
    2023: 'свод  Иркутская область верн 2023г..xls',
    2024: 'свод область 2024г.ф.33,8 верн Иркутская обл.xls'
}

original_url = {}
path = 'E:/IrkutskProject/Data/'

df_2200 = {}

# Путь, где лежит орининальный файл
for year in years:
    original_path = f'{path}{year}/Original/'
    original_url[year] = original_path + original_names[year]
    
    if year == 2016:
        df = pd.read_excel(original_url[year], engine='openpyxl', sheet_name=2)

        # Отфильтруем таблицу 2200
        df_2200[year] = df.head(17)

        # Удаляем пустые столбцы
        df_2200[year] = df_2200[year].dropna(how='all', axis=1)

        df_2200[year] = df_2200[year].drop(df_2200[year].columns[3:4], axis=1)
        # df_2200[year] = df_2200[year].drop(df_2200[year].columns[1:2], axis=1)   # графа с номерами  

        # Удаляем лишние строки
        #df_2200[year].drop(df_2200[year].index[3:5], inplace=True) # строка с номерами
        df_2200[year].drop(df_2200[year].index[3:4], inplace=True) # строка с номерами
        
        df_2200[year].drop(df_2200[year].index[0:1], inplace=True)

    else:
        df = pd.read_excel(original_url[year], engine='xlrd', sheet_name = '2200-2300')

        df_2200[year] = df.head(15)
        df_2200[year] = df_2200[year].dropna(how='all', axis=1)
        df_2200[year] = df_2200[year].drop(df_2200[year].columns[2:3], axis=1)
        #df_2200[year] = df_2200[year].drop(df_2200[year].columns[1:2], axis=1)
        
        #df_2200[year].drop(df_2200[year].index[2:3], inplace=True)

        if (year == 2021):
            df_2200[year] = df_2200[year].drop(df_2200[year].columns[1:2], axis=1)
        
        if (year >= 2020):
            df_2200[year] = df_2200[year].drop(df_2200[year].columns[5:6], axis=1)
            df_2200[year] = df_2200[year].drop(df_2200[year].columns[3:4], axis=1)

    df_2200[year].columns = [0, 1, 2, 3, 4]

    df_2200[year] = df_2200[year].reset_index(drop=True)
    
    df_2200[year].iloc[3, 0] = 'Впервые выявлено больных туберкулезом из числа осмотренных на туберкулез'
    df_2200[year].iloc[4, 0] = 'Впервые выявлено больных туберкулезом из числа осмотренных на туберкулез из них с применением туберкулинодиагностики'
    df_2200[year].iloc[5, 0] = 'Впервые выявлено больных туберкулезом из числа осмотренных на туберкулез в том числе аллергена туберкулезного рекомбинантного в стандартном разведении'
    df_2200[year].iloc[6, 0] = 'Впервые выявлено больных туберкулезом из числа осмотренных на туберкулез из них с применением флюрографии'
    df_2200[year].iloc[7, 0] = 'Впервые выявлено больных туберкулезом из числа осмотренных на туберкулез из них с применением бактериологических методов'
    df_2200[year].iloc[8, 0] = 'Впервые выявлено больных туберкулезом из числа осмотренных на туберкулез в том числе методом бактериоскопии'
    df_2200[year].iloc[9, 0] = 'Взято на учет в III группу диспансерного учета'
    df_2200[year].iloc[10, 0] = 'Взято на учет в V группу диспансерного учета всего'
    df_2200[year].iloc[11, 0] = 'Взято на учет в V группу диспансерного учета в том числе VA'
    df_2200[year].iloc[12, 0] = 'Взято на учет в V группу диспансерного учета в том числе VБ'
    df_2200[year].iloc[13, 0] = 'Кроме того умерло больных от туберкулеза постоянных жителей, диагноз у которых установлен посмертно'
    df_2200[year].iloc[14, 0] = 'Кроме того умерло больных от ВИЧ-инфекции постоянных жителей, диагноз туберкулеза у которых установлен посмертно'

    df_2200[year].iloc[1, 2] = 'Всего'
    df_2200[year].iloc[1, 3] = 'Из них детей от 0 до 14 лет'
    df_2200[year].iloc[1, 4] = 'Из них подростков от 15 до 17 лет'


    for j in range(1, 6):
        df_2200[year].iloc[2, j - 1] = f'{j}'

    for i in range(1, 13):
        df_2200[year].iloc[i + 2, 1] = f'{i}'

    
    # Выкладываем подготовленные данные в файл
    df_2200[year].to_csv(f'E:/IrkutskProject/Data/{year}/2200.csv', index=False)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14704\3132320119.py:94: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_2200[year].iloc[2, j - 1] = f'{j}'

In [9]:
df_2200[2016]

,0,1,2,3,4
0,Наименование показателей,NaN,Всего,из них:,NaN
1,NaN,NaN,Всего,Из них детей от 0 до 14 лет,Из них подростков от 15 до 17 лет
2,1,2,3,4,5
3,Впервые выявлено больных туберкулезом из числа...,1,1601,86,27
4,Впервые выявлено больных туберкулезом из числа...,2,97,86,11
5,Впервые выявлено больных туберкулезом из числа...,3,NaN,NaN,NaN
6,Впервые выявлено больных туберкулезом из числа...,4,1472,NaN,16
7,Впервые выявлено больных туберкулезом из числа...,5,32,NaN,NaN
8,Впервые выявлено больных туберкулезом из числа...,6,32,NaN,NaN
9,Взято на учет в III группу диспансерного учета,7,63,56,7
10,Взято на учет в V группу диспансерного учета в...,8,6,6,NaN
11,Взято на учет в V группу диспансерного учета в...,9,3,3,NaN
12,Взято на учет в V группу диспансерного учета в...,10,2,2,NaN
13,Кроме того умерло больных от туберкулеза посто...,11,22,NaN,NaN
14,Кроме того умерло больных от ВИЧ-инфекции пост...,12,4,NaN,NaN

In [10]:
# df_2200[2017]

In [11]:
#df_2200[2024]

2) Подготовка сводного датасета 2200.csv

In [13]:
columns = [
    'Наименование показателя',
    'Уточнение',
    'Год',
    'Значение',
    'Строка',
    'Графа',
    'Таблица'
]

data = []
data_2016_2018 = []

df_2200_long = pd.DataFrame(columns=columns)
df_2200_long_2016_2018 = pd.DataFrame(columns=columns)

for year in years:
    for row_number in range(3, df_2200[year].shape[0]):
        for col_number in range(2, 5):
            new_row = []
            new_row.append(df_2200[year].iloc[row_number, 0].strip())
            new_row.append(df_2200[year].iloc[1, col_number])
            new_row.append(year)
            #new_row.append(df_2200[year].iloc[row_number, col_number] if pd.notnull(df_2200[year].iloc[row_number, col_number]) else 0)

            new_row.append(df_2200[year].iloc[row_number, col_number] if (
                (df_2200[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2200[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            
            new_row.append(df_2200[year].iloc[row_number, 1])
            new_row.append(df_2200[year].iloc[2, col_number])
            new_row.append(2200)
            data.append(new_row)

            if year <= 2018:
                data_2016_2018.append(new_row)
            
df_2200_long = pd.DataFrame(data, columns=columns)
df_2200_long_2016_2018 = pd.DataFrame(data_2016_2018, columns=columns)

df_2200_long

,Наименование показателя,Уточнение,Год,Значение,Строка,Графа,Таблица
0,Впервые выявлено больных туберкулезом из числа...,Всего,2016,1601.0,1,3,2200
1,Впервые выявлено больных туберкулезом из числа...,Из них детей от 0 до 14 лет,2016,86.0,1,4,2200
2,Впервые выявлено больных туберкулезом из числа...,Из них подростков от 15 до 17 лет,2016,27.0,1,5,2200
3,Впервые выявлено больных туберкулезом из числа...,Всего,2016,97.0,2,3,2200
4,Впервые выявлено больных туберкулезом из числа...,Из них детей от 0 до 14 лет,2016,86.0,2,4,2200
...,...,...,...,...,...,...,...
319,Кроме того умерло больных от туберкулеза посто...,Из них детей от 0 до 14 лет,2024,0.0,11,4,2200
320,Кроме того умерло больных от туберкулеза посто...,Из них подростков от 15 до 17 лет,2024,0.0,11,5,2200
321,Кроме того умерло больных от ВИЧ-инфекции пост...,Всего,2024,0.0,12,3,2200
322,Кроме того умерло больных от ВИЧ-инфекции пост...,Из них детей от 0 до 14 лет,2024,0.0,12,4,2200
323,Кроме того умерло больных от ВИЧ-инфекции пост...,Из них подростков от 15 до 17 лет,2024,0.0,12,5,2200

In [14]:
df_2200_long_2016_2018.to_csv(f'{path}Common_2016-2018/2200_2016-2018.csv', index=False)
df_2200_long.to_csv(f'{path}Common/2200_2016-2024.csv', index=False)