**Подготовка файла 2300.csv на основе данных сводных файлов 2016-2018 годов**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

`..\Data\{год}\` - папка для хранения созданнного 2300.csv для определенного года
`..\Data\{год}\Original` - папка для хранения оригинального файла xlsx
`..\Data\Common\` - папка для хранения итогового результата 2300.csv сводный
Пример:

E:/IrkutskProject/Data/2016/Original/ф33 правл за 2016г Иркутская обл.xlsx
E:/IrkutskProject/Data/2016/2300.csv

In [4]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [5]:
# Установка библиотеки для чтения excel. 
# !pip install openpyxl
# !pip install xlrd

1) Подкотовка датасетов формы 2300 за 2016-2018 года

In [7]:
# Список годов для обработки
#years = [2016, 2017, 2018]

# Название оригинального файла
#original_names = {
#    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
#    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
#    2018: 'ф.33 и ф.8  Иркутская область  2018.xls'
#}

years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

# Название оригинального файла
original_names = {
    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
    2018: 'ф.33 и ф.8  Иркутская область  2018.xls',
    2019: 'Свод ф.33 ,ф.8 область правильный 03.02. 2019.xls',
    2020: 'Свод ф.33,8  Иркутская область 2020 верный.xls',
    2021: 'свод область 2021  верный .xls',
    2022: 'свод верн Иркутская область 2022г  ф.33, 8.xls',
    2023: 'свод  Иркутская область верн 2023г..xls',
    2024: 'свод область 2024г.ф.33,8 верн Иркутская обл.xls'
}

original_url = {}
path = 'E:/IrkutskProject/Data/'

df_2300 = {}

for year in years:
    original_path = f'{path}{year}/Original/'
    original_url[year] = original_path + original_names[year]
    
    if year == 2016:
        df = pd.read_excel(original_url[year], engine='openpyxl', sheet_name = '2200,2300,2310')

        # Отфильтруем таблицу 2300
        df_2300[year] = df.iloc[20:32]
    else:
        df = pd.read_excel(original_url[year], engine='xlrd', sheet_name='2200-2300')

        df_2300[year] = df.iloc[17:29]
        df_2300[year] = df_2300[year].drop(df_2300[year].columns[2:3], axis=1)

    df_2300[year] = df_2300[year].dropna(how='all', axis=1)
    #df_2300[year] = df_2300[year].drop(df_2300[year].columns[1:2], axis=1)
    #df_2300[year].drop(df_2300[year].index[3:4], inplace=True)

    df_2300[year].columns = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 

    # Метки в соотвтетсвии с шаблоном
    df_2300[year].iloc[4, 0] = 'Взято на учет рецидивов'
    df_2300[year].iloc[5, 0] = 'Взято на учет рецидивов III группы'
    df_2300[year].iloc[6, 0] = 'Прибыло'
    df_2300[year].iloc[7, 0] = 'Переведено в III группу'
    df_2300[year].iloc[8, 0] = 'Диагноз туберкулеза снят'
    df_2300[year].iloc[9, 0] = 'Выбыло'
    df_2300[year].iloc[10, 0] = 'Умерло от туберкулеза'
    df_2300[year].iloc[11, 0] = 'Умерло от других причин'

    df_2300[year].iloc[0, 2] = 'Туберкулез органов дыхания'
    df_2300[year].iloc[1, 5] = 'Туберкулез органов дыхания из них туберкулез легких'
    df_2300[year].iloc[0, 8] = 'Прочие формы туберкулеза'

    df_2300[year].iloc[2, 2] = 'Всего'
    df_2300[year].iloc[2, 5] = 'Всего'
    df_2300[year].iloc[2, 8] = 'Всего'

    df_2300[year].iloc[2, 3] = 'Дети от 0 до 14 лет'
    df_2300[year].iloc[2, 6] = 'Дети от 0 до 14 лет'
    df_2300[year].iloc[2, 9] = 'Дети от 0 до 14 лет'

    df_2300[year].iloc[2, 4] = 'Подростки от 15 до 17 лет'
    df_2300[year].iloc[2, 7] = 'Подростки от 15 до 17 лет'
    df_2300[year].iloc[2, 10] = 'Подростки от 15 до 17 лет'
    
    df_2300[year] = df_2300[year].reset_index(drop=True)

    for j in range(1, 12):
        df_2300[year].iloc[3, j - 1] = f'{j}'

    for i in range(1, 9):
        df_2300[year].iloc[i + 3, 1] = f'{i}'
        
    df_2300[year].to_csv(f'E:/IrkutskProject/Data/{year}/2300.csv', index=False)

In [8]:
df_2300[2016]

,0,1,2,3,4,5,6,7,8,9,10
0,NaN,№ стр,Туберкулез органов дыхания,NaN,NaN,NaN,NaN,NaN,Прочие формы туберкулеза,NaN,NaN
1,NaN,NaN,Всего,NaN,NaN,Туберкулез органов дыхания из них туберкулез л...,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Всего,Дети от 0 до 14 лет,Подростки от 15 до 17 лет,Всего,Дети от 0 до 14 лет,Подростки от 15 до 17 лет,Всего,Дети от 0 до 14 лет,Подростки от 15 до 17 лет
3,1,2,3,4,5,6,7,8,9,10,11
4,Взято на учет рецидивов,1,285,NaN,1,274,NaN,1,10,NaN,NaN
5,Взято на учет рецидивов III группы,2,96,NaN,1,93,NaN,1,5,NaN,NaN
6,Прибыло,3,1098,18,4,926,11,4,61,3,1
7,Переведено в III группу,4,2531,127,26,2393,48,21,106,3,NaN
8,Диагноз туберкулеза снят,5,30,3,NaN,26,NaN,NaN,1,NaN,NaN
9,Выбыло,6,760,27,18,639,13,14,47,1,1
10,Умерло от туберкулеза,7,451,NaN,NaN,422,NaN,NaN,12,2,NaN
11,Умерло от других причин,8,708,NaN,NaN,676,NaN,NaN,26,NaN,NaN

In [9]:
columns = [
    'Показатель',
    'Уточнение',
    'Еще уточнение',
    'Год',
    'Значение',
    'Строка',
    'Графа',
    'Таблица'
]

data = []
data_2016_2018 = []

df_2300_long = pd.DataFrame(columns=columns)
df_2300_long_2016_2018 = pd.DataFrame(columns=columns)

for year in years:
    for row_number in range(4, df_2300[year].shape[0]):
        for col_number in range(2, 5):
            new_row = []
            new_row.append(df_2300[year].iloc[row_number, 0]) 
            new_row.append(df_2300[year].iloc[0, 2])
            new_row.append(df_2300[year].iloc[2, col_number])
            new_row.append(year)
            #new_row.append(df_2300[year].iloc[row_number, col_number] if pd.notnull(df_2300[year].iloc[row_number, col_number]) else 0)
            
            new_row.append(df_2300[year].iloc[row_number, col_number] if (
                (df_2300[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2300[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            
            new_row.append(df_2300[year].iloc[row_number, 1])
            new_row.append(df_2300[year].iloc[3, col_number])
            new_row.append(2300)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)
        
        for col_number in range(5, 8):
            new_row = []
            new_row.append(df_2300[year].iloc[row_number, 0]) 
            new_row.append(df_2300[year].iloc[1, 5])
            new_row.append(df_2300[year].iloc[2, col_number])
            new_row.append(year)
            #new_row.append(df_2300[year].iloc[row_number, col_number] if pd.notnull(df_2300[year].iloc[row_number, col_number]) else 0)

            new_row.append(df_2300[year].iloc[row_number, col_number] if (
                (df_2300[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2300[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            
            new_row.append(df_2300[year].iloc[row_number, 1])
            new_row.append(df_2300[year].iloc[3, col_number])
            new_row.append(2300)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)

        for col_number in range(8, 11):
            new_row = []
            new_row.append(df_2300[year].iloc[row_number, 0]) 
            new_row.append(df_2300[year].iloc[0, 8])
            new_row.append(df_2300[year].iloc[2, col_number])
            new_row.append(year)
            #new_row.append(df_2300[year].iloc[row_number, col_number] if pd.notnull(df_2300[year].iloc[row_number, col_number]) else 0)

            new_row.append(df_2300[year].iloc[row_number, col_number] if (
                (df_2300[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2300[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            
            new_row.append(df_2300[year].iloc[row_number, 1])
            new_row.append(df_2300[year].iloc[3, col_number])
            new_row.append(2300)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)

df_2300_long = pd.DataFrame(data, columns=columns)
df_2300_long_2016_2018 = pd.DataFrame(data_2016_2018, columns=columns)

display(df_2300_long)

,Показатель,Уточнение,Еще уточнение,Год,Значение,Строка,Графа,Таблица
0,Взято на учет рецидивов,Туберкулез органов дыхания,Всего,2016,285.0,1,3,2300
1,Взято на учет рецидивов,Туберкулез органов дыхания,Дети от 0 до 14 лет,2016,NaN,1,4,2300
2,Взято на учет рецидивов,Туберкулез органов дыхания,Подростки от 15 до 17 лет,2016,1.0,1,5,2300
3,Взято на учет рецидивов,Туберкулез органов дыхания из них туберкулез л...,Всего,2016,274.0,1,6,2300
4,Взято на учет рецидивов,Туберкулез органов дыхания из них туберкулез л...,Дети от 0 до 14 лет,2016,NaN,1,7,2300
...,...,...,...,...,...,...,...,...
643,Умерло от других причин,Туберкулез органов дыхания из них туберкулез л...,Дети от 0 до 14 лет,2024,0.0,8,7,2300
644,Умерло от других причин,Туберкулез органов дыхания из них туберкулез л...,Подростки от 15 до 17 лет,2024,0.0,8,8,2300
645,Умерло от других причин,Прочие формы туберкулеза,Всего,2024,8.0,8,9,2300
646,Умерло от других причин,Прочие формы туберкулеза,Дети от 0 до 14 лет,2024,0.0,8,10,2300
647,Умерло от других причин,Прочие формы туберкулеза,Подростки от 15 до 17 лет,2024,0.0,8,11,2300

In [10]:
df_2300_long_2016_2018.to_csv(f'{path}Common_2016-2018/2300_2016-2018.csv', index=False)
df_2300_long.to_csv(f'{path}Common/2300_2016-2024.csv', index=False)