**Подготовка файла 2400.csv на основе данных сводных файлов 2016-2018 годов**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

`..\Data\{год}\` - папка для хранения созданнного 2400.csv для определенного года
`..\Data\{год}\Original` - папка для хранения оригинального файла xlsx
`..\Data\Common\` - папка для хранения итогового результата 2400.csv сводный
Пример:

E:/IrkutskProject/Data/2016/Original/ф33 правл за 2016г Иркутская обл.xlsx
E:/IrkutskProject/Data/2016/2400.csv

In [4]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [5]:
# Установка библиотеки для чтения excel. 
# !pip install openpyxl
# !pip install xlrd

1) Подкотовка датасетов формы 2300 за 2016-2018 года

In [7]:
# Список годов для обработки
years = [2016, 2017, 2018]

# Название оригинального файла
original_names = {
    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
    2018: 'ф.33 и ф.8  Иркутская область  2018.xls'
}
original_url = {}
path = 'E:/IrkutskProject/Data/'

df_2400 = {}

for year in years:
    original_path = f'{path}{year}/Original/'
    original_url[year] = original_path + original_names[year]
    
    if year == 2016:
        df = pd.read_excel(original_url[year], engine='openpyxl', sheet_name = '2320,2330,2400')

        # Отфильтруем таблицу 2400
        df_2400[year] = df.iloc[9:27]
    else:
        df = pd.read_excel(original_url[year], engine='xlrd', sheet_name='2400-2500')
        df_2400[year] = df.iloc[0:16]
        df_2400[year] = df_2400[year].drop(df_2400[year].columns[1:8], axis=1)
        
    df_2400[year] = df_2400[year].dropna(how='all', axis=1)
    df_2400[year] = df_2400[year].drop(df_2400[year].columns[1:2], axis=1)
    df_2400[year] = df_2400[year].iloc[:, :8]
    df_2400[year] = df_2400[year].dropna(how='all')
    df_2400[year].drop(df_2400[year].index[1:2], inplace=True)
    
    df_2400[year].columns = [0, 1, 2, 3, 4, 5, 6, 7]
    df_2400[year] = df_2400[year].reset_index(drop=True)

    # Метки в соотвтетсвии с шаблоном
    df_2400[year].iloc[1, 0] = 'Взрослые, из них нуждающиеся в определении активности туберкулезного процесса (0А)'
    df_2400[year].iloc[2, 0] = 'Взрослые, из них нуждающиеся в проведении дифференциально-диагностических мероприятий (0Б)'
    df_2400[year].iloc[3, 0] = 'Взрослые с неактивным туб процессом после канонического излечения (III)'
    df_2400[year].iloc[4, 0] = 'Взрослые, состоящие в бытовом и производственном контакте с бактериовыделителем (IVA)'
    df_2400[year].iloc[5, 0] = 'Взрослые, состоящие в бытовом и производственном контакте с больным туберкулезом без бактериовыделения (IVA)'
    df_2400[year].iloc[6, 0] = 'Взрослые, состоящие в профессиональном контакте с источником инфекции (IVБ)'
    df_2400[year].iloc[7, 0] = 'Дети от 0 до 17 лет, из них нуждающиеся в уточнении характера туберкулезной чувствительности, уточнении активности туберкулеза и диагностике (0)'
    df_2400[year].iloc[8, 0] = 'Дети от 0 до 17 лет с остаточными посттуберкулезными изменениями (IIIА)'
    df_2400[year].iloc[9, 0] = 'Дети от 0 до 17 лет переведнные из I, II, IIIA групп (IIIБ)'
    df_2400[year].iloc[10, 0] = 'Дети от 0 до 17 лет, состоящие  в контакте с бактериовыделителями (IVA)'
    df_2400[year].iloc[11, 0] = 'Дети от 0 до 17 лет из контакта с больными туберкулезом без бактериовыделения, из семей животноводов или имеющих больных туберкулезом животных (IVБ)'
    df_2400[year].iloc[12, 0] = 'Дети от 0 до 17 лет в раннем периоде первичной туберкулезной инфекции (VIA)'
    df_2400[year].iloc[13, 0] = 'Дети от 0 до 17 лет ранее инфецированные, с гиперергической реакцией на туберкулин из соц групп риска с выраженными реакциями на туберкулин (VIБ)'
    df_2400[year].iloc[14, 0] = 'Дети от 0 до 17 лет с усиливающейся туберкулиновой чувствительностью (VIB)'

    df_2400[year].iloc[0, 1] = 'Взято на учет в текущем году'
    df_2400[year].iloc[0, 2] = 'Подлежало ХП или пробному лечению'
    df_2400[year].iloc[0, 3] = 'Прошел курс ХП, пробного лечения'
    df_2400[year].iloc[0, 4] = 'Впервые выявлено больных с ТБ'
    df_2400[year].iloc[0, 5] = 'Снято с учета'
    df_2400[year].iloc[0, 6] = 'Выбыло'
    df_2400[year].iloc[0, 7] = 'Состоит на конец года'

    df_2400[year].to_csv(f'E:/IrkutskProject/Data/{year}/2400.csv')

In [8]:
df_2400[2016]

,0,1,2,3,4,5,6,7
0,Состоит по группам учета,Взято на учет в текущем году,Подлежало ХП или пробному лечению,"Прошел курс ХП, пробного лечения",Впервые выявлено больных с ТБ,Снято с учета,Выбыло,Состоит на конец года
1,"Взрослые, из них нуждающиеся в определении акт...",441,431,391,150,289,21,109
2,"Взрослые, из них нуждающиеся в проведении дифф...",450,245,210,184,281,11,45
3,Взрослые с неактивным туб процессом после кано...,2531,3418,3170,101,2312,377,4948
4,"Взрослые, состоящие в бытовом и производственн...",1211,1743,1575,14,1008,194,2622
5,"Взрослые, состоящие в бытовом и производственн...",1329,1272,1122,1,1379,311,1981
6,"Взрослые, состоящие в профессиональном контакт...",187,173,166,NaN,80,57,1952
7,"Дети от 0 до 17 лет, из них нуждающиеся в уточ...",325,164,163,21,358,24,197
8,Дети от 0 до 17 лет с остаточными посттуберкул...,63,63,63,NaN,36,3,63
9,"Дети от 0 до 17 лет переведнные из I, II, IIIA...",219,219,219,1,212,12,377
10,"Дети от 0 до 17 лет, состоящие в контакте с б...",764,1313,1275,15,661,77,1789
11,Дети от 0 до 17 лет из контакта с больными туб...,1553,1297,1246,NaN,879,65,2773
12,Дети от 0 до 17 лет в раннем периоде первичной...,3667,1865,1801,4,3897,119,3831
13,"Дети от 0 до 17 лет ранее инфецированные, с ги...",859,737,698,NaN,952,33,1101
14,Дети от 0 до 17 лет с усиливающейся туберкулин...,1664,788,723,1,1523,24,1661

In [9]:
# df_2400[2017]

In [10]:
# df_2400[2018]

In [11]:
columns = [
    'Показатель',
    'Уточнение',
    'Год',
    'Значение'
]

data = []

df_2400_long = pd.DataFrame(columns=columns)

for year in years:
    for row_number in range(1, df_2400[year].shape[0]):
        for col_number in range(1, 8):
            new_row = []
            new_row.append(df_2400[year].iloc[row_number, 0]) 
            new_row.append(df_2400[year].iloc[0, col_number])
            new_row.append(year)
            new_row.append(df_2400[year].iloc[row_number, col_number] if pd.notnull(df_2400[year].iloc[row_number, col_number]) else 0)
            data.append(new_row)

df_2400_long = pd.DataFrame(data, columns=columns)

display(df_2400_long)

,Показатель,Уточнение,Год,Значение
0,"Взрослые, из них нуждающиеся в определении акт...",Взято на учет в текущем году,2016,441
1,"Взрослые, из них нуждающиеся в определении акт...",Подлежало ХП или пробному лечению,2016,431
2,"Взрослые, из них нуждающиеся в определении акт...","Прошел курс ХП, пробного лечения",2016,391
3,"Взрослые, из них нуждающиеся в определении акт...",Впервые выявлено больных с ТБ,2016,150
4,"Взрослые, из них нуждающиеся в определении акт...",Снято с учета,2016,289
...,...,...,...,...
289,Дети от 0 до 17 лет с усиливающейся туберкулин...,"Прошел курс ХП, пробного лечения",2018,559
290,Дети от 0 до 17 лет с усиливающейся туберкулин...,Впервые выявлено больных с ТБ,2018,0
291,Дети от 0 до 17 лет с усиливающейся туберкулин...,Снято с учета,2018,1557
292,Дети от 0 до 17 лет с усиливающейся туберкулин...,Выбыло,2018,37
293,Дети от 0 до 17 лет с усиливающейся туберкулин...,Состоит на конец года,2018,1307

In [12]:
df_2400_long.to_csv(f'{path}Common/2400_2016-2018.csv', index=False)