**Подготовка файла 2500.csv на основе данных сводных файлов 2016-2018 годов**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

`..\Data\{год}\` - папка для хранения созданнного 2500.csv для определенного года
`..\Data\{год}\Original` - папка для хранения оригинального файла xlsx
`..\Data\Common\` - папка для хранения итогового результата 2500.csv сводный
Пример:

E:/IrkutskProject/Data/2016/Original/ф33 правл за 2016г Иркутская обл.xlsx
E:/IrkutskProject/Data/2016/2500.csv

In [4]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [5]:
# Установка библиотеки для чтения excel. 
# !pip install openpyxl
# !pip install xlrd

1) Подкотовка датасетов формы 2500 за 2016-2018 года

In [7]:
# Список годов для обработки
#years = [2016, 2017, 2018]

# Название оригинального файла
#original_names = {
#    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
#    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
#    2018: 'ф.33 и ф.8  Иркутская область  2018.xls'
#}

years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

# Название оригинального файла
original_names = {
    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
    2018: 'ф.33 и ф.8  Иркутская область  2018.xls',
    2019: 'Свод ф.33 ,ф.8 область правильный 03.02. 2019.xls',
    2020: 'Свод ф.33,8  Иркутская область 2020 верный.xls',
    2021: 'свод область 2021  верный .xls',
    2022: 'свод верн Иркутская область 2022г  ф.33, 8.xls',
    2023: 'свод  Иркутская область верн 2023г..xls',
    2024: 'свод область 2024г.ф.33,8 верн Иркутская обл.xls'
}
original_url = {}
path = 'E:/IrkutskProject/Data/'

df_2500 = {}

for year in years:
    original_path = f'{path}{year}/Original/'
    original_url[year] = original_path + original_names[year]
    
    if year == 2016:
        df = pd.read_excel(original_url[year], engine='openpyxl', sheet_name = '2500,2510,2520')

        # Отфильтруем таблицу 2500
        df_2500[year] = df.iloc[1:14]
    else:
        df = pd.read_excel(original_url[year], engine='xlrd', sheet_name='2400-2500')
        df_2500[year] = df.iloc[18:28]
    
    df_2500[year] = df_2500[year].dropna(how='all', axis=1)
    df_2500[year] = df_2500[year].dropna(how='all')
    df_2500[year] = df_2500[year].iloc[:, :16]
    #df_2500[year] = df_2500[year].drop(df_2500[year].columns[1:2], axis=1)
    #df_2500[year].drop(df_2500[year].index[3:4], inplace=True)

    df_2500[year] = df_2500[year].reset_index(drop=True)
    df_2500[year].columns = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

    df_2500[year].iloc[4, 0] = 'Туберкулез органов дыхания'
    df_2500[year].iloc[5, 0] = 'Обследовано на МЛУ (из стр1)'
    df_2500[year].iloc[6, 0] = 'Обследовано на МЛУ из них выявлена МЛУ'
    df_2500[year].iloc[7, 0] = 'Туберкулез внелегочных локализаций'
    df_2500[year].iloc[8, 0] = 'Туберкулез внелегочных локализаций, из них сельских жителей (из суммы строк 1 и 4)'

    df_2500[year].iloc[0, 2] = 'Обнаружено из числа больных' 
    df_2500[year].iloc[1, 2] = 'с впервые в жизни установленным диагнозом'
    df_2500[year].iloc[1, 3] = 'из них методом посева'
    df_2500[year].iloc[1, 4] = 'из них методом микроскопии'
    df_2500[year].iloc[1, 5] = 'состоящих на учете'
    df_2500[year].iloc[2, 5] = 'в I группе'
    df_2500[year].iloc[2, 6] = 'из них в IБ группе'
    df_2500[year].iloc[2, 7] = 'в II группе'
    df_2500[year].iloc[2, 8] = 'в III группе'
    df_2500[year].iloc[2, 9] = 'снятых ранее с учета'
    df_2500[year].iloc[0, 10] = 'Переведено из других учреждений бюджетных, выделяющих МБТ'
    df_2500[year].iloc[2, 10] = np.nan
    
    df_2500[year].iloc[0, 11] = 'Умерло'
    df_2500[year].iloc[1, 11] = 'от туберкулеза'
    df_2500[year].iloc[1, 12] = 'от других причин'
    df_2500[year].iloc[0, 13] = 'Перестало выделять МБТ'
    df_2500[year].iloc[0, 14] = 'Выбыло из района обслуживания'
    df_2500[year].iloc[0, 15] = 'Состоит на конец отчетного года'

    for j in range(1, 17):
        df_2500[year].iloc[3, j - 1] = f'{j}'

    for i in range(1, 6):
        df_2500[year].iloc[i + 3, 1] = f'{i}'

    df_2500[year].to_csv(f'E:/IrkutskProject/Data/{year}/2500.csv', index=False)

In [8]:
display(df_2500[2016])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Группы больных,№ стр.,Обнаружено из числа больных,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Переведено из других учреждений бюджетных, выд...",Умерло,NaN,Перестало выделять МБТ,Выбыло из района обслуживания,Состоит на конец отчетного года
1,NaN,NaN,с впервые в жизни установленным диагнозом,из них методом посева,из них методом микроскопии,состоящих на учете,NaN,NaN,NaN,NaN,NaN,от туберкулеза,от других причин,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,в I группе,из них в IБ группе,в II группе,в III группе,снятых ранее с учета,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
4,Туберкулез органов дыхания,1,1027,337,707,253,57,155,44,103,383,248,390,1441,296,2601
5,Обследовано на МЛУ (из стр1),2,1019,318,701,253,56,152,44,100,383,230,388,1414,291,2596
6,Обследовано на МЛУ из них выявлена МЛУ,3,167,154,13,140,32,108,17,34,173,96,154,302,107,1076
7,Туберкулез внелегочных локализаций,4,9,6,3,2,1,3,NaN,NaN,2,NaN,1,10,4,30
8,"Туберкулез внелегочных локализаций, из них сел...",5,296,97,199,50,20,37,9,24,67,89,88,389,111,632

In [9]:
# display(df_2500[2017])

In [10]:
# display(df_2500[2018])

In [11]:
columns = [
    'Показатель',
    'Уточнение',
    'Год',
    'Значение',
    'Строка',
    'Графа',
    'Таблица'
]

data = []
data_2016_2018 = []

df_2500_long = pd.DataFrame(columns=columns)
df_2500_long_2016_2018 = pd.DataFrame(columns=columns)

for year in years:
    for row_number in range(4, df_2500[year].shape[0]):
        for col_number in range(2, 10):
            new_row = []
            new_row.append(df_2500[year].iloc[row_number, 0])
            title_0 = df_2500[year].iloc[0, 2] # Обнаружено из числа больных
            title_1 = ' ' + df_2500[year].iloc[1, 5] # Обнаружено из числа больных состоящих на учете
            title_2 = ' ' + df_2500[year].iloc[2, 5] # Обнаружено из числа больных состоящих на учете в I группе
            title_3 = ' ' + df_2500[year].iloc[2, 6] # Обнаружено из числа больных состоящих на учете в I группе из них в IБ группе

            if (col_number == 2): 
                new_row.append(title_0 + ' ' + df_2500[year].iloc[1, col_number])
            elif(col_number == 3) or (col_number == 4):
                new_row.append(title_0 + ' ' + df_2500[year].iloc[1, 2] + ' ' + df_2500[year].iloc[1, col_number])
            elif (col_number == 5):
                new_row.append(title_0 + title_1 + title_2)
            elif (col_number == 6):
                new_row.append(title_0 + title_1 + title_2 + title_3)
            elif (col_number == 9):
                new_row.append(title_0 + ' ' + df_2500[year].iloc[2, col_number])
            else:
                new_row.append(title_0 + title_1 + ' ' + df_2500[year].iloc[2, col_number])
            new_row.append(year)
            #new_row.append(df_2500[year].iloc[row_number, col_number] if pd.notnull(df_2500[year].iloc[row_number, col_number]) else 0)
            
            new_row.append(df_2500[year].iloc[row_number, col_number] if (
                (df_2500[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2500[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            
            new_row.append(df_2500[year].iloc[row_number,1])
            new_row.append(df_2500[year].iloc[3, col_number])
            new_row.append(2500)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)

        col_number = 10
        new_row = []
        new_row.append(df_2500[year].iloc[row_number, 0])
        new_row.append(df_2500[year].iloc[0, col_number])
        new_row.append(year)
        #new_row.append(df_2500[year].iloc[row_number, col_number] if pd.notnull(df_2500[year].iloc[row_number, col_number]) else 0)

        new_row.append(df_2500[year].iloc[row_number, col_number] if (
            (df_2500[year].iloc[row_number, col_number] != 'X') and # английская X
            (df_2500[year].iloc[row_number, col_number] != 'Х')) # русская Х
        else np.nan)
        
        new_row.append(df_2500[year].iloc[row_number,1])
        new_row.append(df_2500[year].iloc[3, col_number])
        new_row.append(2500)
        data.append(new_row)
        if year <= 2018:
            data_2016_2018.append(new_row)

        for col_number in range(11, 13):
            new_row = []
            new_row.append(df_2500[year].iloc[row_number, 0])
            new_row.append(df_2500[year].iloc[0, 11] + ' ' + df_2500[year].iloc[1, col_number])
            new_row.append(year)
            #new_row.append(df_2500[year].iloc[row_number, col_number] if pd.notnull(df_2500[year].iloc[row_number, col_number]) else 0)

            new_row.append(df_2500[year].iloc[row_number, col_number] if (
                (df_2500[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2500[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            
            new_row.append(df_2500[year].iloc[row_number,1])
            new_row.append(df_2500[year].iloc[3, col_number])
            new_row.append(2500)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)

        for col_number in range(13, 16):
            new_row = []
            new_row.append(df_2500[year].iloc[row_number, 0])
            new_row.append(df_2500[year].iloc[0, col_number])
            new_row.append(year)
            #new_row.append(df_2500[year].iloc[row_number, col_number] if pd.notnull(df_2500[year].iloc[row_number, col_number]) else 0)
            
            new_row.append(df_2500[year].iloc[row_number, col_number] if (
                (df_2500[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2500[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            
            new_row.append(df_2500[year].iloc[row_number,1])
            new_row.append(df_2500[year].iloc[3, col_number])
            new_row.append(2500)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)

df_2500_long = pd.DataFrame(data, columns=columns)
df_2500_long_2016_2018 = pd.DataFrame(data_2016_2018, columns=columns)

display(df_2500_long)

,Показатель,Уточнение,Год,Значение,Строка,Графа,Таблица
0,Туберкулез органов дыхания,Обнаружено из числа больных с впервые в жизни ...,2016,1027.0,1,3,2500
1,Туберкулез органов дыхания,Обнаружено из числа больных с впервые в жизни ...,2016,337.0,1,4,2500
2,Туберкулез органов дыхания,Обнаружено из числа больных с впервые в жизни ...,2016,707.0,1,5,2500
3,Туберкулез органов дыхания,Обнаружено из числа больных состоящих на учете...,2016,253.0,1,6,2500
4,Туберкулез органов дыхания,Обнаружено из числа больных состоящих на учете...,2016,57.0,1,7,2500
...,...,...,...,...,...,...,...
625,"Туберкулез внелегочных локализаций, из них сел...",Умерло от туберкулеза,2024,18.0,5,12,2500
626,"Туберкулез внелегочных локализаций, из них сел...",Умерло от других причин,2024,26.0,5,13,2500
627,"Туберкулез внелегочных локализаций, из них сел...",Перестало выделять МБТ,2024,208.0,5,14,2500
628,"Туберкулез внелегочных локализаций, из них сел...",Выбыло из района обслуживания,2024,34.0,5,15,2500
629,"Туберкулез внелегочных локализаций, из них сел...",Состоит на конец отчетного года,2024,210.0,5,16,2500

In [12]:
df_2500_long_2016_2018.to_csv(f'{path}Common_2016-2018/2500_2016-2018.csv', index=False)
df_2500_long.to_csv(f'{path}Common/2500_2016-2024.csv', index=False)