**Подготовка файла 2600.csv на основе данных сводных файлов 2016-2018 годов**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

`..\Data\{год}\` - папка для хранения созданнного 2600.csv для определенного года
`..\Data\{год}\Original` - папка для хранения оригинального файла xlsx
`..\Data\Common\` - папка для хранения итогового результата 2600.csv сводный
Пример:

E:/IrkutskProject/Data/2016/Original/ф33 правл за 2016г Иркутская обл.xlsx
E:/IrkutskProject/Data/2016/2600.csv

In [4]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [5]:
# Установка библиотеки для чтения excel. 
# !pip install openpyxl
# !pip install xlrd

1) Подкотовка датасетов формы 2600 за 2016-2018 года

In [7]:
# Список годов для обработки
#years = [2016, 2017, 2018]

# Название оригинального файла
#original_names = {
#    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
#    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
#    2018: 'ф.33 и ф.8  Иркутская область  2018.xls'
#}

years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

# Название оригинального файла
original_names = {
    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
    2018: 'ф.33 и ф.8  Иркутская область  2018.xls',
    2019: 'Свод ф.33 ,ф.8 область правильный 03.02. 2019.xls',
    2020: 'Свод ф.33,8  Иркутская область 2020 верный.xls',
    2021: 'свод область 2021  верный .xls',
    2022: 'свод верн Иркутская область 2022г  ф.33, 8.xls',
    2023: 'свод  Иркутская область верн 2023г..xls',
    2024: 'свод область 2024г.ф.33,8 верн Иркутская обл.xls'
}

original_url = {}
path = 'E:/IrkutskProject/Data/'

df_2600 = {}

for year in years:
    original_path = f'{path}{year}/Original/'
    original_url[year] = original_path + original_names[year]
    
    if year == 2016:
        df = pd.read_excel(original_url[year], engine='openpyxl', sheet_name = '2600-2610')

        # Отфильтруем таблицу 2600
        df_2600[year] = df.iloc[2:18]
    else:
        df = pd.read_excel(original_url[year], engine='xlrd', sheet_name='2600-2800')
        df_2600[year] = df.iloc[0:18]
        df_2600[year] = df_2600[year].drop(df_2600[year].columns[10:11], axis=1)
        df_2600[year] = df_2600[year].drop(df_2600[year].columns[ 4: 5], axis=1)

    df_2600[year] = df_2600[year].dropna(how='all', axis=1)
    df_2600[year] = df_2600[year].iloc[:, :8]
    df_2600[year] = df_2600[year].dropna(how='all')
    #df_2600[year].drop(df_2600[year].index[3:4], inplace=True)
    df_2600[year].drop(df_2600[year].index[1:2], inplace=True)
    #df_2600[year] = df_2600[year].drop(df_2600[year].columns[ 1: 2], axis=1)
  
    df_2600[year] = df_2600[year].reset_index(drop=True)

    df_2600[year].columns = [0, 1, 2, 3, 4, 5, 6, 7]

    df_2600[year].iloc[3, 0] = 'Госпитализировано всего'
    df_2600[year].iloc[4, 0] = 'Госпитализировано всего, из них бактериовыделителей'
    df_2600[year].iloc[5, 0] = 'Госпитализировано всего, из них бактериовыделителей, в том числе дневные стационары'
    df_2600[year].iloc[6, 0] = 'Госпитализировано всего, из них бактериовыделителей, в том числе санатории'
    df_2600[year].iloc[7, 0] = 'Применены хирургические методы лечения всего'
    df_2600[year].iloc[8, 0] = 'Применены хирургические методы лечения по поводу туберкулеза органов дыхания'
    df_2600[year].iloc[9, 0] = 'Применены хирургические методы лечения по поводу ФКТ легких'
    df_2600[year].iloc[10, 0] = 'Применены хирургические методы лечения костно-суставного туберкулеза'
    df_2600[year].iloc[11, 0] = 'Применены хирургические методы лечения туберкулеза мочеполовых органов'
    df_2600[year].iloc[12, 0] = 'Применены хирургические методы лечения мочеполовых органов из низ с туберкулезом женских половых органов'
    df_2600[year].iloc[13, 0] = 'Применены хирургические методы лечения туберкулеза периферических лимфатических узлов'
    df_2600[year].iloc[14, 0] = 'Умерло в стационаре от туберкулеза больных, состоявших на учете'

    df_2600[year].iloc[0, 2] = 'Больных состоящих на учете'
    df_2600[year].iloc[1, 2] = 'всего'
    df_2600[year].iloc[1, 3] = 'из них детей до 14 лет'
    df_2600[year].iloc[1, 4] = 'из них подростков 15-17 лет'

    df_2600[year].iloc[0, 5] = 'из них с впервые в жизни установленным диагнозом'
    df_2600[year].iloc[1, 5] = 'всего'
    df_2600[year].iloc[1, 6] = 'из них детей до 14 лет'
    df_2600[year].iloc[1, 7] = 'из них подростков 15-17 лет'

    for j in range(1, 8):
        df_2600[year].iloc[2, j - 1] = f'{j}'

    for i in range(1, 13):
        df_2600[year].iloc[i + 2, 1] = f'{i}'

    df_2600[year].to_csv(f'E:/IrkutskProject/Data/{year}/2600.csv', index=False)

In [8]:
display(df_2600[2016])

,0,1,2,3,4,5,6,7
0,Вид помощи,№ стр.,Больных состоящих на учете,NaN,NaN,из них с впервые в жизни установленным диагнозом,NaN,NaN
1,NaN,NaN,всего,из них детей до 14 лет,из них подростков 15-17 лет,всего,из них детей до 14 лет,из них подростков 15-17 лет
2,1,2,3,4,5,6,7,8
3,Госпитализировано всего,1,4276,109,35,1842,93,31
4,"Госпитализировано всего, из них бактериовыдели...",2,2222,2,10,928,NaN,9
5,"Госпитализировано всего, из них бактериовыдели...",3,335,NaN,NaN,122,NaN,NaN
6,"Госпитализировано всего, из них бактериовыдели...",4,88,1,NaN,12,NaN,NaN
7,Применены хирургические методы лечения всего,5,480,6,4,349,4,3
8,Применены хирургические методы лечения по пово...,6,424,3,4,332,1,3
9,Применены хирургические методы лечения по пово...,7,177,NaN,NaN,8,NaN,NaN
10,Применены хирургические методы лечения костно-...,8,33,3,NaN,6,3,NaN
11,Применены хирургические методы лечения туберку...,9,5,NaN,NaN,2,NaN,NaN
12,Применены хирургические методы лечения мочепол...,10,1,NaN,NaN,1,NaN,NaN
13,Применены хирургические методы лечения туберку...,11,18,NaN,NaN,9,NaN,NaN
14,"Умерло в стационаре от туберкулеза больных, со...",12,228,2,NaN,75,2,NaN

In [9]:
#display(df_2600[2017])

In [10]:
#display(df_2600[2018])

In [11]:
columns = [
    'Показатель',
    'Возраст',
    'Год',
    'Значение',
    'Строка',
    'Графа',
    'Таблица'
]
data = []
data_2016_2018 = []

df_2600_long = pd.DataFrame(columns=columns)
df_2600_long_2016_2018 = pd.DataFrame(columns=columns)


for year in years:
    for row_number in range(3, df_2600[year].shape[0]):
        for col_number in range(2, 5):
            new_row = []
            new_row.append(df_2600[year].iloc[row_number, 0])
            new_row.append(df_2600[year].iloc[0, 2] + ' ' + df_2600[year].iloc[1, col_number])
            new_row.append(year)
            #new_row.append(df_2600[year].iloc[row_number, col_number] if pd.notnull(df_2600[year].iloc[row_number, col_number]) else 0)
            new_row.append(df_2600[year].iloc[row_number, col_number] if (
                (df_2600[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2600[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            new_row.append(df_2600[year].iloc[row_number, 1])
            new_row.append(df_2600[year].iloc[2, col_number])
            new_row.append(2600)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)
            
        for col_number in range(5, 8):
            new_row = []
            new_row.append(df_2600[year].iloc[row_number, 0])
            new_row.append(df_2600[year].iloc[0, 2] + ', ' + df_2600[year].iloc[0, 5] + ' ' +  df_2600[year].iloc[1, col_number])
            new_row.append(year)
            #new_row.append(df_2600[year].iloc[row_number, col_number] if pd.notnull(df_2600[year].iloc[row_number, col_number]) else 0)
            new_row.append(df_2600[year].iloc[row_number, col_number] if (
                (df_2600[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2600[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            new_row.append(df_2600[year].iloc[row_number, 1])
            new_row.append(df_2600[year].iloc[2, col_number])
            new_row.append(2600)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)

df_2600_long = pd.DataFrame(data, columns=columns)
df_2600_long_2016_2018 = pd.DataFrame(data_2016_2018, columns=columns)

display(df_2600_long)

,Показатель,Возраст,Год,Значение,Строка,Графа,Таблица
0,Госпитализировано всего,Больных состоящих на учете всего,2016,4276.0,1,3,2600
1,Госпитализировано всего,Больных состоящих на учете из них детей до 14 лет,2016,109.0,1,4,2600
2,Госпитализировано всего,Больных состоящих на учете из них подростков 1...,2016,35.0,1,5,2600
3,Госпитализировано всего,"Больных состоящих на учете, из них с впервые в...",2016,1842.0,1,6,2600
4,Госпитализировано всего,"Больных состоящих на учете, из них с впервые в...",2016,93.0,1,7,2600
...,...,...,...,...,...,...,...
643,"Умерло в стационаре от туберкулеза больных, со...",Больных состоящих на учете из них детей до 14 лет,2024,0.0,12,4,2600
644,"Умерло в стационаре от туберкулеза больных, со...",Больных состоящих на учете из них подростков 1...,2024,0.0,12,5,2600
645,"Умерло в стационаре от туберкулеза больных, со...","Больных состоящих на учете, из них с впервые в...",2024,24.0,12,6,2600
646,"Умерло в стационаре от туберкулеза больных, со...","Больных состоящих на учете, из них с впервые в...",2024,0.0,12,7,2600
647,"Умерло в стационаре от туберкулеза больных, со...","Больных состоящих на учете, из них с впервые в...",2024,0.0,12,8,2600

In [12]:
df_2600_long_2016_2018.to_csv(f'{path}Common_2016-2018/2600_2016-2018.csv', index=False)
df_2600_long.to_csv(f'{path}Common/2600_2016-2024.csv', index=False)