**Подготовка файла 2700.csv на основе данных сводных файлов 2016-2018 годов**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

`..\Data\{год}\` - папка для хранения созданнного 2700.csv для определенного года
`..\Data\{год}\Original` - папка для хранения оригинального файла xlsx
`..\Data\Common\` - папка для хранения итогового результата 2700.csv сводный
Пример:

E:/IrkutskProject/Data/2016/Original/ф33 правл за 2016г Иркутская обл.xlsx
E:/IrkutskProject/Data/2016/2700.csv

In [4]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [5]:
# Установка библиотеки для чтения excel. 
# !pip install openpyxl
# !pip install xlrd

1) Подкотовка датасетов формы 2700 за 2016-2018 года

In [7]:
# Список годов для обработки
#years = [2016, 2017, 2018]

# Название оригинального файла
#original_names = {
#    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
#    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
#    2018: 'ф.33 и ф.8  Иркутская область  2018.xls'
#}

years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

# Название оригинального файла
original_names = {
    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
    2018: 'ф.33 и ф.8  Иркутская область  2018.xls',
    2019: 'Свод ф.33 ,ф.8 область правильный 03.02. 2019.xls',
    2020: 'Свод ф.33,8  Иркутская область 2020 верный.xls',
    2021: 'свод область 2021  верный .xls',
    2022: 'свод верн Иркутская область 2022г  ф.33, 8.xls',
    2023: 'свод  Иркутская область верн 2023г..xls',
    2024: 'свод область 2024г.ф.33,8 верн Иркутская обл.xls'
}
original_url = {}
path = 'E:/IrkutskProject/Data/'

df_2700 = {}

for year in years:
    original_path = f'{path}{year}/Original/'
    original_url[year] = original_path + original_names[year]
    
    if year == 2016:
        df = pd.read_excel(original_url[year], engine='openpyxl', sheet_name = '2700-2710')

        # Отфильтруем таблицу 2700
        df_2700[year] = df.iloc[2:21]
    else:
        df = pd.read_excel(original_url[year], engine='xlrd', sheet_name='2600-2800')
        df_2700[year] = df.iloc[20:35]
    
    df_2700[year] = df_2700[year].dropna(how='all', axis=1)
    df_2700[year] = df_2700[year].dropna(how='all')
    #df_2700[year] = df_2700[year].drop(df_2700[year].columns[1:2], axis=1)
    #df_2700[year].drop(df_2700[year].index[2:3], inplace=True)
    df_2700[year] = df_2700[year].iloc[:, :10]
    df_2700[year] = df_2700[year].reset_index(drop=True)

    df_2700[year].columns = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

    df_2700[year].iloc[3, 0] = 'Взято на учет в предыдущем году'
    df_2700[year].iloc[4, 0] = 'Выбыло в другие территории'
    df_2700[year].iloc[5, 0] = 'Умерло от туберкулеза'
    df_2700[year].iloc[6, 0] = 'Умерло от других причин'
    df_2700[year].iloc[7, 0] = 'Диагноз туберкулеза снят'
    df_2700[year].iloc[8, 0] = 'Выделение МБТ прекратилось'
    df_2700[year].iloc[9, 0] = 'Полость распада закрылась'
    df_2700[year].iloc[10, 0] = 'Переведено в III группу'
    df_2700[year].iloc[11, 0] = 'Прибыло из других территорий'
    df_2700[year].iloc[12, 0] = 'Выделение МБТ прекратилось 2'
    df_2700[year].iloc[13, 0] = 'Полость распада закрылась 2'
    df_2700[year].iloc[14, 0] = 'Переведено в III группу 2'

    df_2700[year].iloc[0, 2] = 'Впервые выявленные больные'
    df_2700[year].iloc[1, 2] = 'всего'
    df_2700[year].iloc[1, 3] = 'в том числе бактериовыделители'
    df_2700[year].iloc[1, 4] = 'в том числе с деструкцией легочной ткани'
    df_2700[year].iloc[1, 5] = 'без бактериовыделения и деструкции'
    df_2700[year].iloc[0, 6] = 'Больные с рецидивом туберкулеза'
    df_2700[year].iloc[1, 7] = 'всего'
    df_2700[year].iloc[1, 7] = 'в том числе бактериовыделители'
    df_2700[year].iloc[1, 8] = 'в том числе с деструкцией легочной ткани'
    df_2700[year].iloc[1, 9] = 'без бактериовыделения и деструкции'

    for j in range(1, 11):
        df_2700[year].iloc[2, j - 1] = f'{j}'

    for i in range(1, 13):
        df_2700[year].iloc[i + 2, 1] = f'{i}'

    df_2700[year].to_csv(f'E:/IrkutskProject/Data/{year}/2700.csv', index=False)

In [8]:
df_2700[2016]

,0,1,2,3,4,5,6,7,8,9
0,Наименование,№ стр.,Впервые выявленные больные,NaN,NaN,NaN,Больные с рецидивом туберкулеза,NaN,NaN,NaN
1,NaN,NaN,всего,в том числе бактериовыделители,в том числе с деструкцией легочной ткани,без бактериовыделения и деструкции,всего,в том числе бактериовыделители,в том числе с деструкцией легочной ткани,без бактериовыделения и деструкции
2,1,2,3,4,5,6,7,8,9,10
3,Взято на учет в предыдущем году,1,2541,1143,1071,994,336,174,174,106
4,Выбыло в другие территории,2,147,53,42,53,17,8,6,4
5,Умерло от туберкулеза,3,119,74,80,13,22,17,12,2
6,Умерло от других причин,4,302,138,132,97,48,25,20,12
7,Диагноз туберкулеза снят,5,30,2,12,18,1,NaN,1,NaN
8,Выделение МБТ прекратилось,6,NaN,796,NaN,NaN,NaN,88,NaN,NaN
9,Полость распада закрылась,7,NaN,NaN,645,NaN,NaN,NaN,76,NaN
10,Переведено в III группу,8,922,263,257,424,77,22,23,46
11,Прибыло из других территорий,9,202,91,83,67,19,11,10,6
12,Выделение МБТ прекратилось 2,10,NaN,48,NaN,NaN,NaN,10,NaN,NaN
13,Полость распада закрылась 2,11,NaN,NaN,38,NaN,NaN,NaN,6,NaN
14,Переведено в III группу 2,12,89,38,40,45,10,8,3,3

In [9]:
# df_2700[2017]

In [10]:
# df_2700[2018]

In [11]:
columns = [
    'Показатель',
    'Уточнение',
    'Год',
    'Значение',
    'Строка',
    'Графа',
    'Таблица'
]

data = []
data_2016_2018 = []

df_2700_long = pd.DataFrame(columns=columns)
df_2700_long_2016_2018 = pd.DataFrame(columns=columns)

for year in years:
    for row_number in range(3, df_2700[year].shape[0]):
        for col_number in range(2, 6):
            new_row = []
            new_row.append(df_2700[year].iloc[row_number, 0])
            new_row.append(df_2700[year].iloc[0, 2] + ' ' + df_2700[year].iloc[1, col_number])
            new_row.append(year)
            #new_row.append(df_2700[year].iloc[row_number, col_number] if pd.notnull(df_2700[year].iloc[row_number, col_number]) else 0) 
            new_row.append(df_2700[year].iloc[row_number, col_number] if (
                (df_2700[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2700[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            new_row.append(df_2700[year].iloc[row_number, 1])
            new_row.append(df_2700[year].iloc[2, col_number])
            new_row.append(2700)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)

        for col_number in range(6, 10):
            new_row = []
            new_row.append(df_2700[year].iloc[row_number, 0])
            new_row.append(df_2700[year].iloc[0, 6] + ' ' + df_2700[year].iloc[1, col_number])
            new_row.append(year)
            #new_row.append(df_2700[year].iloc[row_number, col_number] if pd.notnull(df_2700[year].iloc[row_number, col_number]) else 0) 
            new_row.append(df_2700[year].iloc[row_number, col_number] if (
                (df_2700[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2700[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            new_row.append(df_2700[year].iloc[row_number, 1])
            new_row.append(df_2700[year].iloc[2, col_number])
            new_row.append(2700)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)

df_2700_long = pd.DataFrame(data, columns=columns)
df_2700_long_2016_2018 = pd.DataFrame(data_2016_2018, columns=columns)

display(df_2700_long)

,Показатель,Уточнение,Год,Значение,Строка,Графа,Таблица
0,Взято на учет в предыдущем году,Впервые выявленные больные всего,2016,2541.0,1,3,2700
1,Взято на учет в предыдущем году,Впервые выявленные больные в том числе бактери...,2016,1143.0,1,4,2700
2,Взято на учет в предыдущем году,Впервые выявленные больные в том числе с дестр...,2016,1071.0,1,5,2700
3,Взято на учет в предыдущем году,Впервые выявленные больные без бактериовыделен...,2016,994.0,1,6,2700
4,Взято на учет в предыдущем году,Больные с рецидивом туберкулеза всего,2016,336.0,1,7,2700
...,...,...,...,...,...,...,...
859,Переведено в III группу 2,Впервые выявленные больные без бактериовыделен...,2024,4.0,12,6,2700
860,Переведено в III группу 2,Больные с рецидивом туберкулеза Всего,2024,0.0,12,7,2700
861,Переведено в III группу 2,Больные с рецидивом туберкулеза в том числе ба...,2024,0.0,12,8,2700
862,Переведено в III группу 2,Больные с рецидивом туберкулеза в том числе с ...,2024,0.0,12,9,2700
863,Переведено в III группу 2,Больные с рецидивом туберкулеза без бактериовы...,2024,0.0,12,10,2700

In [12]:
df_2700_long_2016_2018.to_csv(f'{path}Common_2016-2018/2700_2016-2018.csv', index=False)
df_2700_long.to_csv(f'{path}Common/2700_2016-2024.csv', index=False)