**Рассчет относительных показателей**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

In [3]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [4]:
path = 'E:/IrkutskProject/Data/'

# df_1100 = pd.read_csv(f'{path}Common_2016-2018/1100_2016-2018.csv')
df_1100 = pd.read_csv(f'{path}Common/1100_2016-2024.csv')
# df_population = pd.read_csv(f'{path}Common_2016-2018/avg_population_2016-2018.csv')
df_population = pd.read_csv(f'{path}Common/avg_population_2016-2024.csv')

In [5]:
df_1100

,Показатель,Уточнение,Год,Значение,Строка,Графа,Таблица
0,фтизиатры,"Число должностей в целом по организации, штатных",2016,209.00,110,3,1100
1,фтизиатры,"Число должностей в целом по организации, занятых",2016,197.75,110,4,1100
2,фтизиатры,Число физических лиц основных работников на за...,2016,119.00,110,9,1100
3,из них фтизиатры участковые,"Число должностей в целом по организации, штатных",2016,75.00,111,3,1100
4,из них фтизиатры участковые,"Число должностей в целом по организации, занятых",2016,73.25,111,4,1100
5,из них фтизиатры участковые,Число физических лиц основных работников на за...,2016,36.00,111,9,1100
6,фтизиатры,"Число должностей в целом по организации, штатных",2017,246.25,110,3,1100
7,фтизиатры,"Число должностей в целом по организации, занятых",2017,229.25,110,4,1100
8,фтизиатры,Число физических лиц основных работников на за...,2017,132.00,110,9,1100
9,из них фтизиатры участковые,"Число должностей в целом по организации, штатных",2017,78.25,111,3,1100
10,из них фтизиатры участковые,"Число должностей в целом по организации, занятых",2017,75.50,111,4,1100
11,из них фтизиатры участковые,Число физических лиц основных работников на за...,2017,36.00,111,9,1100
12,фтизиатры,"Число должностей в целом по организации, штатных",2018,230.25,111,3,1100
13,фтизиатры,"Число должностей в целом по организации, занятых",2018,216.75,111,4,1100
14,фтизиатры,Число физических лиц основных работников на за...,2018,127.00,111,9,1100
15,из них фтизиатры участковые,"Число должностей в целом по организации, штатных",2018,73.00,112,3,1100
16,из них фтизиатры участковые,"Число должностей в целом по организации, занятых",2018,70.00,112,4,1100
17,из них фтизиатры участковые,Число физических лиц основных работников на за...,2018,30.00,112,9,1100
18,фтизиатры,"Число должностей в целом по организации, штатных",2019,228.25,110,3,1100
19,фтизиатры,"Число должностей в целом по организации, занятых",2019,216.75,110,4,1100
20,фтизиатры,Число физических лиц основных работников на за...,2019,141.00,110,9,1100
21,из них фтизиатры участковые,"Число должностей в целом по организации, штатных",2019,70.75,111,3,1100
22,из них фтизиатры участковые,"Число должностей в целом по организации, занятых",2019,67.50,111,4,1100
23,из них фтизиатры участковые,Число физических лиц основных работников на за...,2019,43.00,111,9,1100
24,фтизиатры,"Число должностей в целом по организации, штатных",2020,228.50,111,3,1100
25,фтизиатры,"Число должностей в целом по организации, занятых",2020,216.25,111,4,1100
26,фтизиатры,Число физических лиц основных работников на за...,2020,132.00,111,9,1100
27,из них фтизиатры участковые,"Число должностей в целом по организации, штатных",2020,69.25,112,3,1100
28,из них фтизиатры участковые,"Число должностей в целом по организации, занятых",2020,62.75,112,4,1100
29,из них фтизиатры участковые,Число физических лиц основных работников на за...,2020,37.00,112,9,1100
30,фтизиатры,"Число должностей в целом по организации, штатных",2021,236.25,110,3,1100
31,фтизиатры,"Число должностей в целом по организации, занятых",2021,202.75,110,4,1100
32,фтизиатры,Число физических лиц основных работников на за...,2021,133.00,110,9,1100
33,из них фтизиатры участковые,"Число должностей в целом по организации, штатных",2021,72.50,111,3,1100
34,из них фтизиатры участковые,"Число должностей в целом по организации, занятых",2021,62.50,111,4,1100
35,из них фтизиатры участковые,Число физических лиц основных работников на за...,2021,40.00,111,9,1100
36,фтизиатры,"Число должностей в целом по организации, штатных",2022,231.75,111,3,1100
37,фтизиатры,"Число должностей в целом по организации, занятых",2022,202.50,111,4,1100
38,фтизиатры,Число физических лиц основных работников на за...,2022,129.00,111,9,1100
39,из них фтизиатры участковые,"Число должностей в целом по организации, штатных",2022,68.75,112,3,1100
40,из них фтизиатры участковые,"Число должностей в целом по организации, занятых",2022,60.50,112,4,1100
41,из них фтизиатры участковые,Число физических лиц основных работников на за...,2022,38.00,112,9,1100
42,фтизиатры,"Число должностей в целом по организации, штатных",2023,229.50,111,3,1100
43,фтизиатры,"Число должностей в целом по организации, занятых",2023,193.25,111,4,1100
44,фтизиатры,Число физических лиц основных работников на за...,2023,136.00,111,9,1100
45,из них фтизиатры участковые,"Число должностей в целом по организации, штатных",2023,70.75,112,3,1100
46,из них фтизиатры участковые,"Число должностей в целом по организации, занятых",2023,64.25,112,4,1100
47,из них фтизиатры участковые,Число физических лиц основных работников на за...,2023,44.00,112,9,1100
48,фтизиатры,"Число должностей в целом по организации, штатных",2024,201.50,111,3,1100
49,фтизиатры,"Число должностей в целом по организации, занятых",2024,173.75,111,4,1100
50,фтизиатры,Число физических лиц основных работников на за...,2024,121.00,111,9,1100
51,из них фтизиатры участковые,"Число должностей в целом по организации, штатных",2024,71.25,112,3,1100
52,из них фтизиатры участковые,"Число должностей в целом по организации, занятых",2024,66.50,112,4,1100
53,из них фтизиатры участковые,Число физических лиц основных работников на за...,2024,46.00,112,9,1100

In [6]:
df_population

,Год,Пол,Всего,0-4,5-6,7-14,15-17,18-24,25-34,35-44,45-54,55-64,65+,0-14,15+,0-17,18+
0,2016,всего,2410851,183794,69207,235186,74979,190183,409323,348260,291441,318713,289765,488187,1922664,563166,1847685
1,2016,мужчины,1114619,94369,35325,120584,38644,94937,206341,166344,134731,133076,90271,250277,864342,288921,825698
2,2016,женщины,1296232,89425,33883,114603,36336,95247,202982,181917,156710,185638,199495,237910,1058322,274246,1021987
3,2017,всего,2406548,180095,71944,242241,76615,179732,400958,351781,286420,317414,299350,494280,1912269,570895,1835654
4,2017,мужчины,1112389,92675,36680,124173,39412,89836,202508,168114,132457,132864,93673,253527,858862,292939,819451
5,2017,женщины,1294159,87420,35265,118068,37204,89896,198450,183667,153964,184550,205678,240753,1053407,277956,1016203
6,2018,всего,2400979,173758,74222,249204,79314,173837,387116,356380,284386,314232,308532,497183,1903796,576497,1824482
7,2018,мужчины,1109440,89448,37978,127607,40624,87221,195507,170847,131440,131825,96947,255032,854409,295655,813785
8,2018,женщины,1291539,84310,36245,121597,38691,86617,191609,185534,152946,182408,211585,242152,1049388,280842,1010697
9,2019,всего,2394478,166162,73833,257439,81632,171343,372520,360286,285077,308254,317934,497434,1897045,579066,1815413
10,2019,мужчины,1106966,85593,37950,131713,41786,86326,188429,173554,131723,129695,100200,255255,851711,297040,809926
11,2019,женщины,1287513,80570,35883,125727,39847,85017,184092,186732,153355,178559,217734,242179,1045334,282026,1005487
12,2020,всего,2383107,156989,72584,266302,82676,170497,357878,363064,287566,299733,325821,495875,1887233,578551,1804557
13,2020,мужчины,1102145,80884,37333,136219,42330,86258,181466,175607,132744,126549,102757,254436,847709,296766,805379
14,2020,женщины,1280962,76105,35251,130083,40346,84240,176412,187457,154822,173184,223064,241439,1039524,281785,999178
15,2021,всего,2369234,145400,70721,270895,81391,169214,331043,373903,294843,294570,337257,487016,1882219,568407,1800828
16,2021,мужчины,1092153,74826,36411,138610,41847,86206,166696,180203,135627,124839,106891,249846,842307,291693,800460
17,2021,женщины,1277082,70574,34311,132286,39545,83008,164347,193700,159217,169731,230366,237170,1039912,276714,1000368
18,2022,всего,2353904,136960,67889,275874,82513,170290,300100,384840,302033,287228,346178,480722,1873182,563235,1790669
19,2022,мужчины,1081052,70490,35016,141246,42661,87068,149618,184591,138137,122027,110199,246752,834300,289412,791640
20,2022,женщины,1272852,66470,32874,134628,39853,83222,150482,200249,163896,165201,235980,233971,1038882,273823,999029
21,2023,всего,2337449,131475,64080,281069,88298,173439,278524,387437,305264,276137,351728,476624,1860825,564922,1772527
22,2023,мужчины,1072490,67706,32984,144157,45547,88519,139139,185924,138910,117596,112011,244846,827644,290393,782097
23,2023,женщины,1264959,63770,31097,136912,42751,84920,139386,201513,166354,158541,239717,231778,1033181,274529,990430
24,2024,всего,2330537,127771,61716,281377,91717,174343,269012,388659,307305,271701,356936,470864,1859673,562581,1767956
25,2024,мужчины,1068992,65725,31704,144504,47206,89016,134817,186602,139659,115967,113792,241933,827059,289139,779853
26,2024,женщины,1261545,62046,30012,136873,44511,85327,134195,202057,167646,155734,243144,228931,1032614,273442,988103

In [7]:
years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

columns = [
    'id',
    'name',
    'short_name',
    'year',
    'indicator',
    'numerator',
    'denominator'
]

data = []
data_2016_2018 = []

df_table_8 = pd.DataFrame(columns=columns)
df_table_8_2016_2018 = pd.DataFrame(columns=columns)


for year in years:
    new_row = []
    new_row.append('id_8.1')
    new_row.append('Обеспеченность населения фтизиатрами (на 10 000 населения)')
    new_row.append('Врачи туб')
    new_row.append(year)
    
    if (year == 2016) or (year == 2017) or (year == 2019) or (year == 2021):
        print('if = ', year)
        # форма 30, табл.1100,   стр.111,   гр.3) /    Среднегодовая численность населения Иркутской области  * 10000
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]
        denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['Всего'].iloc[0]
    else:
        print('else = ', year)
        # форма 30, табл.1100,   стр.111,   гр.3) /    Среднегодовая численность населения Иркутской области  * 10000
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]
        denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['Всего'].iloc[0]

    if denominator != 0:
        indicator = round(numerator*10000/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
    #----
    new_row = []
    new_row.append('id_8.2')
    new_row.append('Укомплектованность кадрами (%)')
    new_row.append('УК врачи туб')
    new_row.append(year)
    
    if (year == 2016) or (year == 2017) or (year == 2019) or (year == 2021):
        # форма 30, табл.1100,   стр.111,   гр.4) /     форма 30, табл.1100,   стр.111,   гр.3) * 100%
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]
    else:
        # форма 30, табл.1100,   стр.111,   гр.4) /     форма 30, табл.1100,   стр.111,   гр.3) * 100%
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]

    if denominator != 0:
        indicator = round(numerator*100/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
    #----
    new_row = []
    new_row.append('id_8.3')
    new_row.append('Укомплектованность физическими лицами (%)')
    new_row.append('УФ врачи туб')
    new_row.append(year)

    if (year == 2016) or (year == 2017) or (year == 2019) or (year == 2021):    
        # форма 30, табл.1100,   стр.111,   гр.9) /     форма 30, табл.1100,   стр.111,   гр.3) * 100%
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]
    else:
        # форма 30, табл.1100,   стр.111,   гр.9) /     форма 30, табл.1100,   стр.111,   гр.3) * 100%
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]        

    if denominator != 0:
        indicator = round(numerator*100/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
    #----
    new_row = []
    new_row.append('id_8.4')
    new_row.append('Коэффициент совместительства')
    new_row.append('КС врачи туб')
    new_row.append(year)

    if (year == 2016) or (year == 2017) or (year == 2019) or (year == 2021):      
        # форма 30, табл.1100,   стр.111,   гр.4) /     форма 30, табл.1100,   стр.111,   гр.9)
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]
    else:
        # форма 30, табл.1100,   стр.111,   гр.4) /     форма 30, табл.1100,   стр.111,   гр.9)
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]

    if denominator != 0:
        indicator = round(numerator/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
    #----
    new_row = []
    new_row.append('id_8.5')
    new_row.append('Обеспеченность населения фтизиатрами участковыми (на 10 000 населения)')
    new_row.append('Врачи туб участ')
    new_row.append(year)

    if (year == 2016) or (year == 2017) or (year == 2019) or (year == 2021):    
        # форма 30, табл.1100,   стр.112,   гр.3) /    Среднегодовая численность населения Иркутской области  * 10000
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]
        denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['Всего'].iloc[0]
    else:
        # форма 30, табл.1100,   стр.112,   гр.3) /    Среднегодовая численность населения Иркутской области  * 10000
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 112) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]
        denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['Всего'].iloc[0]
    
    if denominator != 0:
        indicator = round(numerator*10000/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
    #----
    new_row = []
    new_row.append('id_8.6')
    new_row.append('Укомплектованность кадрами  фтизиатрами участковыми (%)')
    new_row.append('УК врачи туб участ')
    new_row.append(year)

    if (year == 2016) or (year == 2017) or (year == 2019) or (year == 2021):     
        # форма 30, табл.1100,   стр.112,   гр.4) /     форма 30, табл.1100,   стр.112,   гр.3) * 100%
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]
    else:
        # форма 30, табл.1100,   стр.112,   гр.4) /     форма 30, табл.1100,   стр.112,   гр.3) * 100%
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 112) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 112) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]


    if denominator != 0:
        indicator = round(numerator*100/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
    #----
    new_row = []
    new_row.append('id_8.7')
    new_row.append('Укомплектованность  фтизиатрами участковыми физическими лицами (%)')
    new_row.append('УФ врачи туб участ')
    new_row.append(year)

    if (year == 2016) or (year == 2017) or (year == 2019) or (year == 2021):
        # форма 30, табл.1100,   стр.112,   гр.9) /     форма 30, табл.1100,   стр.112,   гр.3) * 100%
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]
    else:
        # форма 30, табл.1100,   стр.112,   гр.9) /     форма 30, табл.1100,   стр.112,   гр.3) * 100%
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 112) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 112) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]

    if denominator != 0:
        indicator = round(numerator*100/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)    
    #----
    new_row = []
    new_row.append('id_8.8')
    new_row.append('Коэффициент совместительства  фтизиатрами участковыми')
    new_row.append('КС врачи туб участ')
    new_row.append(year)
    
    if (year == 2016) or (year == 2017) or (year == 2019) or (year == 2021):
        # форма 30, табл.1100,   стр.112,   гр.4) /     форма 30, табл.1100,   стр.112,   гр.9)
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]
    else:
        # форма 30, табл.1100,   стр.112,   гр.4) /     форма 30, табл.1100,   стр.112,   гр.9)
        numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 112) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
        denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 112) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]

    if denominator != 0:
        indicator = round(numerator/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
    
    
df_table_8 = pd.DataFrame(data, columns=columns)
df_table_8_2016_2018 = pd.DataFrame(data_2016_2018, columns=columns)

if =  2016
if =  2017
else =  2018
if =  2019
else =  2020
if =  2021
else =  2022
else =  2023
else =  2024

In [8]:
df_table_8.head(30)

,id,name,short_name,year,indicator,numerator,denominator
0,id_8.1,Обеспеченность населения фтизиатрами (на 10 00...,Врачи туб,2016,0.87,209.00,2410851.00
1,id_8.2,Укомплектованность кадрами (%),УК врачи туб,2016,94.62,197.75,209.00
2,id_8.3,Укомплектованность физическими лицами (%),УФ врачи туб,2016,56.94,119.00,209.00
3,id_8.4,Коэффициент совместительства,КС врачи туб,2016,1.66,197.75,119.00
4,id_8.5,Обеспеченность населения фтизиатрами участковы...,Врачи туб участ,2016,0.31,75.00,2410851.00
5,id_8.6,Укомплектованность кадрами фтизиатрами участк...,УК врачи туб участ,2016,97.67,73.25,75.00
6,id_8.7,Укомплектованность фтизиатрами участковыми фи...,УФ врачи туб участ,2016,48.00,36.00,75.00
7,id_8.8,Коэффициент совместительства фтизиатрами учас...,КС врачи туб участ,2016,2.03,73.25,36.00
8,id_8.1,Обеспеченность населения фтизиатрами (на 10 00...,Врачи туб,2017,1.02,246.25,2406548.00
9,id_8.2,Укомплектованность кадрами (%),УК врачи туб,2017,93.10,229.25,246.25
10,id_8.3,Укомплектованность физическими лицами (%),УФ врачи туб,2017,53.60,132.00,246.25
11,id_8.4,Коэффициент совместительства,КС врачи туб,2017,1.74,229.25,132.00
12,id_8.5,Обеспеченность населения фтизиатрами участковы...,Врачи туб участ,2017,0.33,78.25,2406548.00
13,id_8.6,Укомплектованность кадрами фтизиатрами участк...,УК врачи туб участ,2017,96.49,75.50,78.25
14,id_8.7,Укомплектованность фтизиатрами участковыми фи...,УФ врачи туб участ,2017,46.01,36.00,78.25
15,id_8.8,Коэффициент совместительства фтизиатрами учас...,КС врачи туб участ,2017,2.10,75.50,36.00
16,id_8.1,Обеспеченность населения фтизиатрами (на 10 00...,Врачи туб,2018,0.96,230.25,2400979.00
17,id_8.2,Укомплектованность кадрами (%),УК врачи туб,2018,94.14,216.75,230.25
18,id_8.3,Укомплектованность физическими лицами (%),УФ врачи туб,2018,55.16,127.00,230.25
19,id_8.4,Коэффициент совместительства,КС врачи туб,2018,1.71,216.75,127.00
20,id_8.5,Обеспеченность населения фтизиатрами участковы...,Врачи туб участ,2018,0.30,73.00,2400979.00
21,id_8.6,Укомплектованность кадрами фтизиатрами участк...,УК врачи туб участ,2018,95.89,70.00,73.00
22,id_8.7,Укомплектованность фтизиатрами участковыми фи...,УФ врачи туб участ,2018,41.10,30.00,73.00
23,id_8.8,Коэффициент совместительства фтизиатрами учас...,КС врачи туб участ,2018,2.33,70.00,30.00
24,id_8.1,Обеспеченность населения фтизиатрами (на 10 00...,Врачи туб,2019,0.95,228.25,2394478.00
25,id_8.2,Укомплектованность кадрами (%),УК врачи туб,2019,94.96,216.75,228.25
26,id_8.3,Укомплектованность физическими лицами (%),УФ врачи туб,2019,61.77,141.00,228.25
27,id_8.4,Коэффициент совместительства,КС врачи туб,2019,1.54,216.75,141.00
28,id_8.5,Обеспеченность населения фтизиатрами участковы...,Врачи туб участ,2019,0.30,70.75,2394478.00
29,id_8.6,Укомплектованность кадрами фтизиатрами участк...,УК врачи туб участ,2019,95.41,67.50,70.75

In [9]:
df_table_8_2016_2018.to_csv(f'{path}Common_2016-2018/table_8_2016-2018.csv', index=False)
df_table_8.to_csv(f'{path}Common/table_8_2016-2024.csv', index=False)