**Рассчет относительных показателей**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

In [3]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [4]:
path = 'E:/IrkutskProject/Data/'

df_1100 = pd.read_csv(f'{path}Common_2016-2018/1100_2016-2018.csv')
df_population = pd.read_csv(f'{path}Common_2016-2018/avg_population_2016-2018.csv')

In [5]:
df_1100

,Показатель,Уточнение,Год,Значение,Строка,Графа,Таблица
0,Фтизиатры,"Число должностей в целом по организации, штатных",2016,209.00,110,3,1100
1,Фтизиатры,"Число должностей в целом по организации, занятых",2016,197.75,110,4,1100
2,Фтизиатры,Число физических лиц основных работников на за...,2016,NaN,110,9,1100
3,Фтизиатры участковые,"Число должностей в целом по организации, штатных",2016,75.00,111,3,1100
4,Фтизиатры участковые,"Число должностей в целом по организации, занятых",2016,73.25,111,4,1100
5,Фтизиатры участковые,Число физических лиц основных работников на за...,2016,36.00,111,9,1100
6,Фтизиатры,"Число должностей в целом по организации, штатных",2017,246.25,110,3,1100
7,Фтизиатры,"Число должностей в целом по организации, занятых",2017,229.25,110,4,1100
8,Фтизиатры,Число физических лиц основных работников на за...,2017,132.00,110,9,1100
9,Фтизиатры участковые,"Число должностей в целом по организации, штатных",2017,78.25,111,3,1100
10,Фтизиатры участковые,"Число должностей в целом по организации, занятых",2017,75.50,111,4,1100
11,Фтизиатры участковые,Число физических лиц основных работников на за...,2017,36.00,111,9,1100
12,Фтизиатры,"Число должностей в целом по организации, штатных",2018,230.25,110,3,1100
13,Фтизиатры,"Число должностей в целом по организации, занятых",2018,216.75,110,4,1100
14,Фтизиатры,Число физических лиц основных работников на за...,2018,127.00,110,9,1100
15,Фтизиатры участковые,"Число должностей в целом по организации, штатных",2018,73.00,111,3,1100
16,Фтизиатры участковые,"Число должностей в целом по организации, занятых",2018,70.00,111,4,1100
17,Фтизиатры участковые,Число физических лиц основных работников на за...,2018,30.00,111,9,1100

In [6]:
df_population

,Год,Пол,Всего,0-4,5-6,7-14,15-17,18-24,25-34,35-44,45-54,55-64,65+,0-14,15+,0-17
0,2016,всего,2414025,183794,68727,233402,74071,182890,409107,352787,294176,322672,292402,485922,1928103,559993
1,2016,мужчины,1111367,94369,35154,119494,38051,91801,203011,167754,135722,134884,91128,249017,862350,287068
2,2016,женщины,1302658,89425,33573,113908,36020,91089,206096,185033,158454,187789,201274,236905,1065753,272925
3,2017,всего,2410290,180095,71793,240155,75729,172555,397839,357736,289546,321926,302918,492043,1918248,567772
4,2017,мужчины,1108557,92675,36642,123107,38674,86941,197302,169834,133595,134883,94906,252424,856133,291097
5,2017,женщины,1301734,87420,35151,117048,37056,85614,200537,187903,155951,187044,208012,239619,1062115,276675
6,2018,всего,2405290,173758,74222,246918,78222,166956,380953,364027,287779,319292,313166,494898,1910392,573119
7,2018,мужчины,1105027,89448,37978,126670,39603,84422,188693,172916,132626,134038,98635,254095,850932,293697
8,2018,женщины,1300263,84310,36245,120249,38619,82534,192261,191111,155153,185254,214531,240803,1059460,279422

In [7]:
years = [2016, 2017, 2018]

columns = [
    'id',
    'name',
    'short_name',
    'year',
    'indicator',
    'numerator',
    'denominator'
]

data = []

for year in years:
    new_row = []
    new_row.append('id_8.1')
    new_row.append('Обеспеченность населения фтизиатрами (на 10 000 населения)')
    new_row.append('Врачи туб')
    new_row.append(year)
    
    # форма 30, табл.1100,   стр.111,   гр.3) /    Среднегодовая численность населения Иркутской области  * 10000
    numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]
    denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['Всего'].iloc[0]

    if denominator != 0:
        indicator = round(numerator*10000/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    #----
    new_row = []
    new_row.append('id_8.2')
    new_row.append('Укомплектованность кадрами (%)')
    new_row.append('УК врачи туб')
    new_row.append(year)
    
    # форма 30, табл.1100,   стр.111,   гр.4) /     форма 30, табл.1100,   стр.111,   гр.3) * 100%
    numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
    denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]

    if denominator != 0:
        indicator = round(numerator*100/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    #----
    new_row = []
    new_row.append('id_8.3')
    new_row.append('Укомплектованность физическими лицами (%)')
    new_row.append('УФ врачи туб')
    new_row.append(year)
    
    # форма 30, табл.1100,   стр.111,   гр.9) /     форма 30, табл.1100,   стр.111,   гр.3) * 100%
    numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]
    denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]

    if denominator != 0:
        indicator = round(numerator*100/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    #----
    new_row = []
    new_row.append('id_8.4')
    new_row.append('Коэффициент совместительства')
    new_row.append('КС врачи туб')
    new_row.append(year)
    
    # форма 30, табл.1100,   стр.111,   гр.4) /     форма 30, табл.1100,   стр.111,   гр.9)
    numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
    denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 110) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]

    if denominator != 0:
        indicator = round(numerator/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    #----
    new_row = []
    new_row.append('id_8.5')
    new_row.append('Обеспеченность населения фтизиатрами участковыми (на 10 000 населения)')
    new_row.append('Врачи туб участ')
    new_row.append(year)
    
    # форма 30, табл.1100,   стр.112,   гр.3) /    Среднегодовая численность населения Иркутской области  * 10000
    numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]
    denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['Всего'].iloc[0]

    if denominator != 0:
        indicator = round(numerator*10000/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    #----
    new_row = []
    new_row.append('id_8.6')
    new_row.append('Укомплектованность кадрами  фтизиатрами участковыми (%)')
    new_row.append('УК врачи туб участ')
    new_row.append(year)
    
    # форма 30, табл.1100,   стр.112,   гр.4) /     форма 30, табл.1100,   стр.112,   гр.3) * 100%
    numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
    denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]

    if denominator != 0:
        indicator = round(numerator*100/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)

    #----
    new_row = []
    new_row.append('id_8.7')
    new_row.append('Укомплектованность  фтизиатрами участковыми физическими лицами (%)')
    new_row.append('УФ врачи туб участ')
    new_row.append(year)
    
    # форма 30, табл.1100,   стр.112,   гр.9) /     форма 30, табл.1100,   стр.112,   гр.3) * 100%
    numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]
    denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 3)]['Значение'].iloc[0]

    if denominator != 0:
        indicator = round(numerator*100/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    
    #----
    new_row = []
    new_row.append('id_8.8')
    new_row.append('Коэффициент совместительства  фтизиатрами участковыми')
    new_row.append('КС врачи туб участ')
    new_row.append(year)
    
    # форма 30, табл.1100,   стр.112,   гр.4) /     форма 30, табл.1100,   стр.112,   гр.9)
    numerator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 4)]['Значение'].iloc[0]
    denominator = df_1100[(df_1100['Год'] == year) & (df_1100['Строка'] == 111) & (df_1100['Графа'] == 9)]['Значение'].iloc[0]

    if denominator != 0:
        indicator = round(numerator/denominator, 2)
    else:
        indicator = 0.00

    new_row.append(indicator)
    new_row.append(numerator)
    new_row.append(denominator)

    data.append(new_row)
    
    
df_table_8 = pd.DataFrame(data, columns=columns)

In [8]:
df_table_8.head(30)

,id,name,short_name,year,indicator,numerator,denominator
0,id_8.1,Обеспеченность населения фтизиатрами (на 10 00...,Врачи туб,2016,0.87,209.00,2414025.00
1,id_8.2,Укомплектованность кадрами (%),УК врачи туб,2016,94.62,197.75,209.00
2,id_8.3,Укомплектованность физическими лицами (%),УФ врачи туб,2016,NaN,NaN,209.00
3,id_8.4,Коэффициент совместительства,КС врачи туб,2016,NaN,197.75,NaN
4,id_8.5,Обеспеченность населения фтизиатрами участковы...,Врачи туб участ,2016,0.31,75.00,2414025.00
5,id_8.6,Укомплектованность кадрами фтизиатрами участк...,УК врачи туб участ,2016,97.67,73.25,75.00
6,id_8.7,Укомплектованность фтизиатрами участковыми фи...,УФ врачи туб участ,2016,48.00,36.00,75.00
7,id_8.8,Коэффициент совместительства фтизиатрами учас...,КС врачи туб участ,2016,2.03,73.25,36.00
8,id_8.1,Обеспеченность населения фтизиатрами (на 10 00...,Врачи туб,2017,1.02,246.25,2410290.00
9,id_8.2,Укомплектованность кадрами (%),УК врачи туб,2017,93.10,229.25,246.25
10,id_8.3,Укомплектованность физическими лицами (%),УФ врачи туб,2017,53.60,132.00,246.25
11,id_8.4,Коэффициент совместительства,КС врачи туб,2017,1.74,229.25,132.00
12,id_8.5,Обеспеченность населения фтизиатрами участковы...,Врачи туб участ,2017,0.32,78.25,2410290.00
13,id_8.6,Укомплектованность кадрами фтизиатрами участк...,УК врачи туб участ,2017,96.49,75.50,78.25
14,id_8.7,Укомплектованность фтизиатрами участковыми фи...,УФ врачи туб участ,2017,46.01,36.00,78.25
15,id_8.8,Коэффициент совместительства фтизиатрами учас...,КС врачи туб участ,2017,2.10,75.50,36.00
16,id_8.1,Обеспеченность населения фтизиатрами (на 10 00...,Врачи туб,2018,0.96,230.25,2405290.00
17,id_8.2,Укомплектованность кадрами (%),УК врачи туб,2018,94.14,216.75,230.25
18,id_8.3,Укомплектованность физическими лицами (%),УФ врачи туб,2018,55.16,127.00,230.25
19,id_8.4,Коэффициент совместительства,КС врачи туб,2018,1.71,216.75,127.00
20,id_8.5,Обеспеченность населения фтизиатрами участковы...,Врачи туб участ,2018,0.30,73.00,2405290.00
21,id_8.6,Укомплектованность кадрами фтизиатрами участк...,УК врачи туб участ,2018,95.89,70.00,73.00
22,id_8.7,Укомплектованность фтизиатрами участковыми фи...,УФ врачи туб участ,2018,41.10,30.00,73.00
23,id_8.8,Коэффициент совместительства фтизиатрами учас...,КС врачи туб участ,2018,2.33,70.00,30.00

In [9]:
df_table_8.to_csv(f'{path}Common_2016-2018/table_8_2016-2018.csv', index=False)