**Расчет относительных показателей**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

In [3]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [4]:
path = 'E:/IrkutskProject/Data/'

df_population = pd.read_csv(f'{path}Common/avg_population_2016-2024.csv')
df_3100 = pd.read_csv(f'{path}Common/3100_2016-2024.csv')

In [5]:
df_population

,Год,Пол,Всего,0-4,5-6,7-14,15-17,18-24,25-34,35-44,45-54,55-64,65+,0-14,15+,0-17,18+
0,2016,всего,2410851,183794,69207,235186,74979,190183,409323,348260,291441,318713,289765,488187,1922664,563166,1847685
1,2016,мужчины,1114619,94369,35325,120584,38644,94937,206341,166344,134731,133076,90271,250277,864342,288921,825698
2,2016,женщины,1296232,89425,33883,114603,36336,95247,202982,181917,156710,185638,199495,237910,1058322,274246,1021987
3,2017,всего,2406548,180095,71944,242241,76615,179732,400958,351781,286420,317414,299350,494280,1912269,570895,1835654
4,2017,мужчины,1112389,92675,36680,124173,39412,89836,202508,168114,132457,132864,93673,253527,858862,292939,819451
5,2017,женщины,1294159,87420,35265,118068,37204,89896,198450,183667,153964,184550,205678,240753,1053407,277956,1016203
6,2018,всего,2400979,173758,74222,249204,79314,173837,387116,356380,284386,314232,308532,497183,1903796,576497,1824482
7,2018,мужчины,1109440,89448,37978,127607,40624,87221,195507,170847,131440,131825,96947,255032,854409,295655,813785
8,2018,женщины,1291539,84310,36245,121597,38691,86617,191609,185534,152946,182408,211585,242152,1049388,280842,1010697
9,2019,всего,2394478,166162,73833,257439,81632,171343,372520,360286,285077,308254,317934,497434,1897045,579066,1815413
10,2019,мужчины,1106966,85593,37950,131713,41786,86326,188429,173554,131723,129695,100200,255255,851711,297040,809926
11,2019,женщины,1287513,80570,35883,125727,39847,85017,184092,186732,153355,178559,217734,242179,1045334,282026,1005487
12,2020,всего,2383107,156989,72584,266302,82676,170497,357878,363064,287566,299733,325821,495875,1887233,578551,1804557
13,2020,мужчины,1102145,80884,37333,136219,42330,86258,181466,175607,132744,126549,102757,254436,847709,296766,805379
14,2020,женщины,1280962,76105,35251,130083,40346,84240,176412,187457,154822,173184,223064,241439,1039524,281785,999178
15,2021,всего,2369234,145400,70721,270895,81391,169214,331043,373903,294843,294570,337257,487016,1882219,568407,1800828
16,2021,мужчины,1092153,74826,36411,138610,41847,86206,166696,180203,135627,124839,106891,249846,842307,291693,800460
17,2021,женщины,1277082,70574,34311,132286,39545,83008,164347,193700,159217,169731,230366,237170,1039912,276714,1000368
18,2022,всего,2353904,136960,67889,275874,82513,170290,300100,384840,302033,287228,346178,480722,1873182,563235,1790669
19,2022,мужчины,1081052,70490,35016,141246,42661,87068,149618,184591,138137,122027,110199,246752,834300,289412,791640
20,2022,женщины,1272852,66470,32874,134628,39853,83222,150482,200249,163896,165201,235980,233971,1038882,273823,999029
21,2023,всего,2337449,131475,64080,281069,88298,173439,278524,387437,305264,276137,351728,476624,1860825,564922,1772527
22,2023,мужчины,1072490,67706,32984,144157,45547,88519,139139,185924,138910,117596,112011,244846,827644,290393,782097
23,2023,женщины,1264959,63770,31097,136912,42751,84920,139386,201513,166354,158541,239717,231778,1033181,274529,990430
24,2024,всего,2330537,127771,61716,281377,91717,174343,269012,388659,307305,271701,356936,470864,1859673,562581,1767956
25,2024,мужчины,1068992,65725,31704,144504,47206,89016,134817,186602,139659,115967,113792,241933,827059,289139,779853
26,2024,женщины,1261545,62046,30012,136873,44511,85327,134195,202057,167646,155734,243144,228931,1032614,273442,988103

In [6]:
df_3100

,Показатель,Уточнение,Год,Значение,Строка,Графа,Таблица
0,туберкулезные для взрослых,"Число коек, фактически развернутых и свернутых...",2016,1405,57,5,3100
1,туберкулезные для детей,"Число коек, фактически развернутых и свернутых...",2016,150,58,5,3100
2,туберкулезные для взрослых,В отчетном году,2016,5927,57,6,3100
3,туберкулезные для детей,В отчетном году,2016,527,58,6,3100
4,туберкулезные для взрослых,"Число коек, фактически развернутых и свернутых...",2017,1356,57,5,3100
5,туберкулезные для детей,"Число коек, фактически развернутых и свернутых...",2017,150,58,5,3100
6,туберкулезные для взрослых,В отчетном году,2017,5551,57,6,3100
7,туберкулезные для детей,В отчетном году,2017,457,58,6,3100
8,ортопедические для детей,"Число коек, фактически развернутых и свернутых...",2018,14,57,5,3100
9,туберкулезные для взрослых,"Число коек, фактически развернутых и свернутых...",2018,1334,58,5,3100
10,ортопедические для детей,В отчетном году,2018,285,57,6,3100
11,туберкулезные для взрослых,В отчетном году,2018,5544,58,6,3100
12,туберкулезные для взрослых,"Число коек, фактически развернутых и свернутых...",2019,1324,57,5,3100
13,туберкулезные для детей,"Число коек, фактически развернутых и свернутых...",2019,95,58,5,3100
14,туберкулезные для взрослых,В отчетном году,2019,5094,57,6,3100
15,туберкулезные для детей,В отчетном году,2019,304,58,6,3100
16,ортопедические для детей,"Число коек, фактически развернутых и свернутых...",2020,7,57,5,3100
17,туберкулезные для взрослых,"Число коек, фактически развернутых и свернутых...",2020,1278,58,5,3100
18,ортопедические для детей,В отчетном году,2020,218,57,6,3100
19,туберкулезные для взрослых,В отчетном году,2020,4358,58,6,3100
20,туберкулезные для взрослых,"Число коек, фактически развернутых и свернутых...",2021,1188,57,5,3100
21,туберкулезные для детей,"Число коек, фактически развернутых и свернутых...",2021,90,58,5,3100
22,туберкулезные для взрослых,В отчетном году,2021,4218,57,6,3100
23,туберкулезные для детей,В отчетном году,2021,314,58,6,3100
24,туберкулезные для взрослых,"Число коек, фактически развернутых и свернутых...",2022,1189,57,5,3100
25,туберкулезные для детей,"Число коек, фактически развернутых и свернутых...",2022,90,58,5,3100
26,туберкулезные для взрослых,В отчетном году,2022,4378,57,6,3100
27,туберкулезные для детей,В отчетном году,2022,353,58,6,3100
28,туберкулезные для взрослых,"Число коек, фактически развернутых и свернутых...",2023,1189,57,5,3100
29,туберкулезные для детей,"Число коек, фактически развернутых и свернутых...",2023,90,58,5,3100
30,туберкулезные для взрослых,В отчетном году,2023,4215,57,6,3100
31,туберкулезные для детей,В отчетном году,2023,320,58,6,3100
32,туберкулезные для взрослых,"Число коек, фактически развернутых и свернутых...",2024,1173,57,5,3100
33,туберкулезные для детей,"Число коек, фактически развернутых и свернутых...",2024,90,58,5,3100
34,туберкулезные для взрослых,В отчетном году,2024,4220,57,6,3100
35,туберкулезные для детей,В отчетном году,2024,344,58,6,3100

In [7]:
df_3100.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Показатель  36 non-null     object
 1   Уточнение   36 non-null     object
 2   Год         36 non-null     int64
 3   Значение    36 non-null     int64
 4   Строка      36 non-null     int64
 5   Графа       36 non-null     int64
 6   Таблица     36 non-null     int64
dtypes: int64(5), object(2)
memory usage: 2.1+ KB

In [8]:
years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
columns = [
    'id',
    'name',
    'short_name',
    'year',
    'indicator',
    'numerator',
    'denominator'
]

data = []
data_2016_2018 = []

df_table_9 = pd.DataFrame(columns=columns)
df_table_9_2016_2018 = pd.DataFrame(columns=columns)

for year in years:
    new_row = []
    # id_9.1 форма 30, табл.3100,   стр.57,   гр.5) /    Среднегодовая численность населения Иркутской области  * 10000
    new_row.append('id_9.1')
    new_row.append('Обеспеченность населения туберкулезными койками  для взрослых (на 10 000 населения)')
    new_row.append('Койки туб вз')
    new_row.append(year)
    numerator = df_3100[(df_3100['Год'] == year) & (df_3100['Строка'] == 57) & (df_3100['Графа'] == 5)]['Значение'].iloc[0]
    denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['18+'].iloc[0]
    #print('year = ', year, 'numerator = ', numerator, 'denominator =', denominator)
    indicator = numerator* 10000/denominator
    new_row.append(round(indicator, 2))
    new_row.append(numerator)
    new_row.append(denominator)
    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)

#---------------------
    new_row = []
    # id_9.2 форма 30, табл.3100,   стр.58,   гр.5) /    Среднегодовая численность детского населения (0-17 лет) Иркутской области  * 10000
    new_row.append('id_9.2')
    new_row.append('Обеспеченность населения туберкулезными койками  для детей (на 10 000 населения)')
    new_row.append('Койки туб дет')
    new_row.append(year)
    numerator = df_3100[(df_3100['Год'] == year) & (df_3100['Строка'] == 58) & (df_3100['Графа'] == 5)]['Значение'].iloc[0]
    denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['0-17'].iloc[0]
    #print('year = ', year, 'numerator = ', numerator, 'denominator =', denominator)
    indicator = numerator* 10000/denominator
    new_row.append(round(indicator, 2))
    new_row.append(numerator)
    new_row.append(denominator)
    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
        
#-------------------------
    new_row = []
    # id_9.3 форма 30, табл.3100,   стр.57,   гр.6 /    Среднегодовая численность взрослого (18 и старше)населения Иркутской области  * 100000
    new_row.append('id_9.3')
    new_row.append('Госпитализированная заболеваемость взрослого населения (на 100 тыс. населения)')
    new_row.append('ГЗ взр')
    new_row.append(year)
    numerator = df_3100[(df_3100['Год'] == year) & (df_3100['Строка'] == 57) & (df_3100['Графа'] == 6)]['Значение'].iloc[0]
    denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['18+'].iloc[0]
    #print('year = ', year, 'numerator = ', numerator, 'denominator =', denominator)
    indicator = numerator* 100000/denominator
    new_row.append(round(indicator, 2))
    new_row.append(numerator)
    new_row.append(denominator)
    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
        
#------------------------
    new_row = []
    # id_9.4 форма 30, табл.3100,   стр.58,   гр.6) /    Среднегодовая численность детского населения (0-17 лет) Иркутской области  * 100000
    new_row.append('id_9.4')
    new_row.append('Госпитализированная заболеваемость детского населения 0-17 (на 100 тыс. населения)')
    new_row.append('ГЗ дети 0-17')
    new_row.append(year)
    numerator = df_3100[(df_3100['Год'] == year) & (df_3100['Строка'] == 58) & (df_3100['Графа'] == 6)]['Значение'].iloc[0]
    denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['0-17'].iloc[0]
    #print('year = ', year, 'numerator = ', numerator, 'denominator =', denominator)
    indicator = numerator* 100000/denominator
    new_row.append(round(indicator, 2))
    new_row.append(numerator)
    new_row.append(denominator)
    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)

  
df_table_9 = pd.DataFrame(data, columns=columns)
df_table_9_2016_2018 = pd.DataFrame(data_2016_2018, columns=columns)
df_table_9

,id,name,short_name,year,indicator,numerator,denominator
0,id_9.1,Обеспеченность населения туберкулезными койкам...,Койки туб вз,2016,7.60,1405,1847685
1,id_9.2,Обеспеченность населения туберкулезными койкам...,Койки туб дет,2016,2.66,150,563166
2,id_9.3,Госпитализированная заболеваемость взрослого н...,ГЗ взр,2016,320.78,5927,1847685
3,id_9.4,Госпитализированная заболеваемость детского на...,ГЗ дети 0-17,2016,93.58,527,563166
4,id_9.1,Обеспеченность населения туберкулезными койкам...,Койки туб вз,2017,7.39,1356,1835654
5,id_9.2,Обеспеченность населения туберкулезными койкам...,Койки туб дет,2017,2.63,150,570895
6,id_9.3,Госпитализированная заболеваемость взрослого н...,ГЗ взр,2017,302.40,5551,1835654
7,id_9.4,Госпитализированная заболеваемость детского на...,ГЗ дети 0-17,2017,80.05,457,570895
8,id_9.1,Обеспеченность населения туберкулезными койкам...,Койки туб вз,2018,0.08,14,1824482
9,id_9.2,Обеспеченность населения туберкулезными койкам...,Койки туб дет,2018,23.14,1334,576497
10,id_9.3,Госпитализированная заболеваемость взрослого н...,ГЗ взр,2018,15.62,285,1824482
11,id_9.4,Госпитализированная заболеваемость детского на...,ГЗ дети 0-17,2018,961.67,5544,576497
12,id_9.1,Обеспеченность населения туберкулезными койкам...,Койки туб вз,2019,7.29,1324,1815413
13,id_9.2,Обеспеченность населения туберкулезными койкам...,Койки туб дет,2019,1.64,95,579066
14,id_9.3,Госпитализированная заболеваемость взрослого н...,ГЗ взр,2019,280.60,5094,1815413
15,id_9.4,Госпитализированная заболеваемость детского на...,ГЗ дети 0-17,2019,52.50,304,579066
16,id_9.1,Обеспеченность населения туберкулезными койкам...,Койки туб вз,2020,0.04,7,1804557
17,id_9.2,Обеспеченность населения туберкулезными койкам...,Койки туб дет,2020,22.09,1278,578551
18,id_9.3,Госпитализированная заболеваемость взрослого н...,ГЗ взр,2020,12.08,218,1804557
19,id_9.4,Госпитализированная заболеваемость детского на...,ГЗ дети 0-17,2020,753.26,4358,578551
20,id_9.1,Обеспеченность населения туберкулезными койкам...,Койки туб вз,2021,6.60,1188,1800828
21,id_9.2,Обеспеченность населения туберкулезными койкам...,Койки туб дет,2021,1.58,90,568407
22,id_9.3,Госпитализированная заболеваемость взрослого н...,ГЗ взр,2021,234.23,4218,1800828
23,id_9.4,Госпитализированная заболеваемость детского на...,ГЗ дети 0-17,2021,55.24,314,568407
24,id_9.1,Обеспеченность населения туберкулезными койкам...,Койки туб вз,2022,6.64,1189,1790669
25,id_9.2,Обеспеченность населения туберкулезными койкам...,Койки туб дет,2022,1.60,90,563235
26,id_9.3,Госпитализированная заболеваемость взрослого н...,ГЗ взр,2022,244.49,4378,1790669
27,id_9.4,Госпитализированная заболеваемость детского на...,ГЗ дети 0-17,2022,62.67,353,563235
28,id_9.1,Обеспеченность населения туберкулезными койкам...,Койки туб вз,2023,6.71,1189,1772527
29,id_9.2,Обеспеченность населения туберкулезными койкам...,Койки туб дет,2023,1.59,90,564922
30,id_9.3,Госпитализированная заболеваемость взрослого н...,ГЗ взр,2023,237.80,4215,1772527
31,id_9.4,Госпитализированная заболеваемость детского на...,ГЗ дети 0-17,2023,56.64,320,564922
32,id_9.1,Обеспеченность населения туберкулезными койкам...,Койки туб вз,2024,6.63,1173,1767956
33,id_9.2,Обеспеченность населения туберкулезными койкам...,Койки туб дет,2024,1.60,90,562581
34,id_9.3,Госпитализированная заболеваемость взрослого н...,ГЗ взр,2024,238.69,4220,1767956
35,id_9.4,Госпитализированная заболеваемость детского на...,ГЗ дети 0-17,2024,61.15,344,562581

In [9]:
df_table_9_2016_2018.to_csv(f'{path}Common_2016-2018/table_9_2016-2018.csv', index=False)
df_table_9.to_csv(f'{path}Common/table_9_2016-2024.csv', index=False)