**Рассчет относительных показателей**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

In [3]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [4]:
path = 'E:/IrkutskProject/Data/'

df_1000 = pd.read_csv(f'{path}Common_2016-2018/1000_2016-2018.csv')
df_population = pd.read_csv(f'{path}Common_2016-2018/avg_population_2016-2018.csv')
#df_1000 = pd.read_csv(f'{path}Common/1000.csv')

In [5]:
df_1000.head(22)

,Формы туберкулеза,Код по МКБ-Х пересмотра,Пол,Возраст,Год,Значение,Строка,Графа,Таблица
0,Впервые выявленный туберкулез всего,A15 - A19,М,всего,2016,1699.0,1,5,1000
1,Впервые выявленный туберкулез всего,A15 - A19,М,0-4,2016,23.0,1,6,1000
2,Впервые выявленный туберкулез всего,A15 - A19,М,5-6,2016,8.0,1,7,1000
3,Впервые выявленный туберкулез всего,A15 - A19,М,7-14,2016,21.0,1,8,1000
4,Впервые выявленный туберкулез всего,A15 - A19,М,15-17,2016,15.0,1,9,1000
5,Впервые выявленный туберкулез всего,A15 - A19,М,18-24,2016,83.0,1,10,1000
6,Впервые выявленный туберкулез всего,A15 - A19,М,25-34,2016,502.0,1,11,1000
7,Впервые выявленный туберкулез всего,A15 - A19,М,35-44,2016,548.0,1,12,1000
8,Впервые выявленный туберкулез всего,A15 - A19,М,45-54,2016,251.0,1,13,1000
9,Впервые выявленный туберкулез всего,A15 - A19,М,55-64,2016,182.0,1,14,1000
10,Впервые выявленный туберкулез всего,A15 - A19,М,65+,2016,66.0,1,15,1000
11,Впервые выявленный туберкулез всего,A15 - A19,Ж,всего,2016,916.0,2,5,1000
12,Впервые выявленный туберкулез всего,A15 - A19,Ж,0-4,2016,15.0,2,6,1000
13,Впервые выявленный туберкулез всего,A15 - A19,Ж,5-6,2016,8.0,2,7,1000
14,Впервые выявленный туберкулез всего,A15 - A19,Ж,7-14,2016,20.0,2,8,1000
15,Впервые выявленный туберкулез всего,A15 - A19,Ж,15-17,2016,18.0,2,9,1000
16,Впервые выявленный туберкулез всего,A15 - A19,Ж,18-24,2016,64.0,2,10,1000
17,Впервые выявленный туберкулез всего,A15 - A19,Ж,25-34,2016,308.0,2,11,1000
18,Впервые выявленный туберкулез всего,A15 - A19,Ж,35-44,2016,257.0,2,12,1000
19,Впервые выявленный туберкулез всего,A15 - A19,Ж,45-54,2016,104.0,2,13,1000
20,Впервые выявленный туберкулез всего,A15 - A19,Ж,55-64,2016,75.0,2,14,1000
21,Впервые выявленный туберкулез всего,A15 - A19,Ж,65+,2016,47.0,2,15,1000

In [6]:
df_population = df_population.rename(columns={'Всего': 'всего'})
df_population['Пол'] = df_population['Пол'].replace({
    'мужчины': 'мужского населения',
    'женщины': 'женского населения'
})
df_population

,Год,Пол,всего,0-4,5-6,7-14,15-17,18-24,25-34,35-44,45-54,55-64,65+,0-14,15+,0-17
0,2016,всего,2414025,183794,68727,233402,74071,182890,409107,352787,294176,322672,292402,485922,1928103,559993
1,2016,мужского населения,1111367,94369,35154,119494,38051,91801,203011,167754,135722,134884,91128,249017,862350,287068
2,2016,женского населения,1302658,89425,33573,113908,36020,91089,206096,185033,158454,187789,201274,236905,1065753,272925
3,2017,всего,2410290,180095,71793,240155,75729,172555,397839,357736,289546,321926,302918,492043,1918248,567772
4,2017,мужского населения,1108557,92675,36642,123107,38674,86941,197302,169834,133595,134883,94906,252424,856133,291097
5,2017,женского населения,1301734,87420,35151,117048,37056,85614,200537,187903,155951,187044,208012,239619,1062115,276675
6,2018,всего,2405290,173758,74222,246918,78222,166956,380953,364027,287779,319292,313166,494898,1910392,573119
7,2018,мужского населения,1105027,89448,37978,126670,39603,84422,188693,172916,132626,134038,98635,254095,850932,293697
8,2018,женского населения,1300263,84310,36245,120249,38619,82534,192261,191111,155153,185254,214531,240803,1059460,279422

In [7]:
df_1000[(df_1000['Год'] == 2016) & (df_1000['Строка'] == 1) & (df_1000['Графа'] == 5)]['Значение'].iloc[0]

1699.0

In [8]:
years = [2016, 2017, 2018]
columns = [
    'id',
    'name',
    'short_name',
    'year',
    'indicator',
    'numerator',
    'denominator'
]

age_group_mapping = {
    'всего': '1',
    '0-4': '4',
    '5-6': '5',
    '7-14': '6',
    '15-17': '7',
    '18-24': '8',
    '25-34': '9',
    '35-44': '10',
    '45-54': '11',
    '55-64': '12',
    '65+': '13'
}

data = []

for row_number in range(0, df_population.shape[0]):
     for col_number in range(2,13):
        new_row = []

        age_group = df_population.columns[col_number]
        base_id = age_group_mapping[age_group]

        if df_population.iloc[row_number, 1] == 'всего':
            id_value = f'id_1.{base_id}'
        elif df_population.iloc[row_number, 1] == 'мужского населения':
            id_value = f'id_1.{base_id}.1'
        else:  # женское население
            id_value = f'id_1.{base_id}.2'
        # display(id_value)

        if id_value == 'id_1.1.1':
            id_value = 'id_1.2'
        if id_value == 'id_1.1.2':
            id_value = 'id_1.3'
            
        new_row.append(id_value)
         
        # new_row.append('id_1.1') # переделать
         
        if df_population.iloc[row_number, 1] == 'всего':
            if df_population.columns[col_number] == 'всего':
                new_row.append(f'Показатель первичной заболеваемости туберкулезом {df_population.columns[col_number]} (на 100 тыс. населения)')
                new_row.append(f'ПЗ туб тер')
            elif (df_population.columns[col_number] == '5-6') or (df_population.columns[col_number] == '7-14') or (df_population.columns[col_number] == '15-17') or (df_population.columns[col_number] == '65+'):
                new_row.append(f'Показатель первичной заболеваемости туберкулезом {df_population.columns[col_number]} лет (на 100 тыс. населения)')
                new_row.append(f'ПЗ туб {df_population.columns[col_number]}')
            else:
                new_row.append(f'Показатель первичной заболеваемости туберкулезом {df_population.columns[col_number]} года (на 100 тыс. населения)')
                new_row.append(f'ПЗ туб {df_population.columns[col_number]}')
        else:
            if df_population.columns[col_number] == 'всего':
                new_row.append(f'Показатель первичной заболеваемости туберкулезом {df_population.iloc[row_number, 1]} {df_population.columns[col_number]} (на 100 тыс. населения)')
                new_row.append(f'ПЗ туб {df_population.iloc[row_number, 1][:3]}')
            elif (df_population.columns[col_number] == '5-6') or (df_population.columns[col_number] == '7-14') or (df_population.columns[col_number] == '15-17') or (df_population.columns[col_number] == '65+'):
                new_row.append(f'Показатель первичной заболеваемости туберкулезом {df_population.iloc[row_number, 1]} {df_population.columns[col_number]} лет (на 100 тыс. населения)')
                new_row.append(f'ПЗ туб {df_population.iloc[row_number, 1][:3]} {df_population.columns[col_number]}')
            else:
                new_row.append(f'Показатель первичной заболеваемости туберкулезом {df_population.iloc[row_number, 1]} {df_population.columns[col_number]} года (на 100 тыс. населения)')
                new_row.append(f'ПЗ туб {df_population.iloc[row_number, 1][:3]} {df_population.columns[col_number]}')
           
        new_row.append(df_population.iloc[row_number, 0]) # год


        if df_population.iloc[row_number, 1] == 'всего': 
        #форма 8, табл.1000,   стр.1+2,   гр.5) / Среднегодовая численность населения Иркутской области* 100000
            value1 = df_1000[(df_1000['Год'] == df_population.iloc[row_number, 0]) & (df_1000['Строка'] == 1) & (df_1000['Графа'] == col_number + 3)]['Значение'].iloc[0]
            value2 = df_1000[(df_1000['Год'] == df_population.iloc[row_number, 0]) & (df_1000['Строка'] == 2) & (df_1000['Графа'] == col_number + 3)]['Значение'].iloc[0]
            numerator = value1 + value2
        elif df_population.iloc[row_number, 1] == 'мужского населения':
            numerator = df_1000[(df_1000['Год'] == df_population.iloc[row_number, 0]) & (df_1000['Строка'] == 1) & (df_1000['Графа'] == col_number + 3)]['Значение'].iloc[0]
        else:
            numerator = df_1000[(df_1000['Год'] == df_population.iloc[row_number, 0]) & (df_1000['Строка'] == 2) & (df_1000['Графа'] == col_number + 3)]['Значение'].iloc[0]

        denominator = df_population.iloc[row_number, col_number]
    
        indicator = numerator * 100000/denominator
    
        new_row.append(round(indicator, 2))
        new_row.append(numerator)
        new_row.append(denominator)
        data.append(new_row)

df_table_1 = pd.DataFrame(data, columns=columns)

In [9]:
df_table_1

,id,name,short_name,year,indicator,numerator,denominator
0,id_1.1,Показатель первичной заболеваемости туберкулез...,ПЗ туб тер,2016,108.33,2615.0,2414025
1,id_1.4,Показатель первичной заболеваемости туберкулез...,ПЗ туб 0-4,2016,20.68,38.0,183794
2,id_1.5,Показатель первичной заболеваемости туберкулез...,ПЗ туб 5-6,2016,23.28,16.0,68727
3,id_1.6,Показатель первичной заболеваемости туберкулез...,ПЗ туб 7-14,2016,17.57,41.0,233402
4,id_1.7,Показатель первичной заболеваемости туберкулез...,ПЗ туб 15-17,2016,44.55,33.0,74071
...,...,...,...,...,...,...,...
94,id_1.9.2,Показатель первичной заболеваемости туберкулез...,ПЗ туб жен 25-34,2018,98.30,189.0,192261
95,id_1.10.2,Показатель первичной заболеваемости туберкулез...,ПЗ туб жен 35-44,2018,113.02,216.0,191111
96,id_1.11.2,Показатель первичной заболеваемости туберкулез...,ПЗ туб жен 45-54,2018,58.01,90.0,155153
97,id_1.12.2,Показатель первичной заболеваемости туберкулез...,ПЗ туб жен 55-64,2018,30.23,56.0,185254
98,id_1.13.2,Показатель первичной заболеваемости туберкулез...,ПЗ туб жен 65+,2018,19.11,41.0,214531

In [10]:
df_table_1.to_csv(f'{path}Common_2016-2018/table_1_2016-2018.csv', index=False)