**Расчет относительных показателей**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

In [3]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [4]:
path = 'E:/IrkutskProject/Data/'

df_population = pd.read_csv(f'{path}Common/avg_population_2016-2024.csv')
df_2513 = pd.read_csv(f'{path}Common/2513_2016-2024.csv')

In [5]:
df_population

,Год,Пол,Всего,0-4,5-6,7-14,15-17,18-24,25-34,35-44,45-54,55-64,65+,0-14,15+,0-17,18+
0,2016,всего,2410851,183794,69207,235186,74979,190183,409323,348260,291441,318713,289765,488187,1922664,563166,1847685
1,2016,мужчины,1114619,94369,35325,120584,38644,94937,206341,166344,134731,133076,90271,250277,864342,288921,825698
2,2016,женщины,1296232,89425,33883,114603,36336,95247,202982,181917,156710,185638,199495,237910,1058322,274246,1021987
3,2017,всего,2406548,180095,71944,242241,76615,179732,400958,351781,286420,317414,299350,494280,1912269,570895,1835654
4,2017,мужчины,1112389,92675,36680,124173,39412,89836,202508,168114,132457,132864,93673,253527,858862,292939,819451
5,2017,женщины,1294159,87420,35265,118068,37204,89896,198450,183667,153964,184550,205678,240753,1053407,277956,1016203
6,2018,всего,2400979,173758,74222,249204,79314,173837,387116,356380,284386,314232,308532,497183,1903796,576497,1824482
7,2018,мужчины,1109440,89448,37978,127607,40624,87221,195507,170847,131440,131825,96947,255032,854409,295655,813785
8,2018,женщины,1291539,84310,36245,121597,38691,86617,191609,185534,152946,182408,211585,242152,1049388,280842,1010697
9,2019,всего,2394478,166162,73833,257439,81632,171343,372520,360286,285077,308254,317934,497434,1897045,579066,1815413
10,2019,мужчины,1106966,85593,37950,131713,41786,86326,188429,173554,131723,129695,100200,255255,851711,297040,809926
11,2019,женщины,1287513,80570,35883,125727,39847,85017,184092,186732,153355,178559,217734,242179,1045334,282026,1005487
12,2020,всего,2383107,156989,72584,266302,82676,170497,357878,363064,287566,299733,325821,495875,1887233,578551,1804557
13,2020,мужчины,1102145,80884,37333,136219,42330,86258,181466,175607,132744,126549,102757,254436,847709,296766,805379
14,2020,женщины,1280962,76105,35251,130083,40346,84240,176412,187457,154822,173184,223064,241439,1039524,281785,999178
15,2021,всего,2369234,145400,70721,270895,81391,169214,331043,373903,294843,294570,337257,487016,1882219,568407,1800828
16,2021,мужчины,1092153,74826,36411,138610,41847,86206,166696,180203,135627,124839,106891,249846,842307,291693,800460
17,2021,женщины,1277082,70574,34311,132286,39545,83008,164347,193700,159217,169731,230366,237170,1039912,276714,1000368
18,2022,всего,2353904,136960,67889,275874,82513,170290,300100,384840,302033,287228,346178,480722,1873182,563235,1790669
19,2022,мужчины,1081052,70490,35016,141246,42661,87068,149618,184591,138137,122027,110199,246752,834300,289412,791640
20,2022,женщины,1272852,66470,32874,134628,39853,83222,150482,200249,163896,165201,235980,233971,1038882,273823,999029
21,2023,всего,2337449,131475,64080,281069,88298,173439,278524,387437,305264,276137,351728,476624,1860825,564922,1772527
22,2023,мужчины,1072490,67706,32984,144157,45547,88519,139139,185924,138910,117596,112011,244846,827644,290393,782097
23,2023,женщины,1264959,63770,31097,136912,42751,84920,139386,201513,166354,158541,239717,231778,1033181,274529,990430
24,2024,всего,2330537,127771,61716,281377,91717,174343,269012,388659,307305,271701,356936,470864,1859673,562581,1767956
25,2024,мужчины,1068992,65725,31704,144504,47206,89016,134817,186602,139659,115967,113792,241933,827059,289139,779853
26,2024,женщины,1261545,62046,30012,136873,44511,85327,134195,202057,167646,155734,243144,228931,1032614,273442,988103

In [6]:
df_2513

,Показатель,Уточнение,Год,Значение,Строка,Графа,Таблица
0,"Осмотрено пациентов, всего",Всего,2016,1892276.0,1,3,2513
1,Из числа осмотренных (стр.1) обследовано флюор...,Всего,2016,1411232.0,2,3,2513
2,Из числа осмотренных (стр.1) обследовано бакте...,Всего,2016,11666.0,3,3,2513
3,Из числа осмотренных детей (стр. 1.1+1.2+1.3) ...,Всего,2016,455644.0,4,3,2513
4,Из числа осмотренных детей (стр. 1.1+1.2+1.3) ...,Всего,2016,NaN,5,3,2513
...,...,...,...,...,...,...,...
58,Из числа осмотренных (стр.1) обследовано бакте...,Всего,2024,2731.0,3,3,2513
59,Из числа осмотренных детей (стр. 1.1+1.2+1.3) ...,Всего,2024,210816.0,4,3,2513
60,Из числа осмотренных детей (стр. 1.1+1.2+1.3) ...,Всего,2024,250750.0,5,3,2513
61,Из числа осмотренных (стр.1) обследовано флюор...,Выявлен туберкулез,2024,699.0,2,5,2513
62,Из числа осмотренных (стр.1) обследовано бакте...,Выявлен туберкулез,2024,33.0,3,5,2513

In [7]:
years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
columns = [
    'id',
    'name',
    'short_name',
    'year',
    'indicator',
    'numerator',
    'denominator'
]

data = []
data_2016_2018 = []

df_table_7 = pd.DataFrame(columns=columns)
df_table_7_2016_2018 = pd.DataFrame(columns=columns)

for year in years:
    new_row = []
    # id_7.1 форма 30, табл.2513,   стр.1,   гр.3) /    Среднегодовая численность населения Иркутской области  * 100%
    new_row.append('id_7.1')
    new_row.append('Охват населения всеми видами осмотров (в %)')
    new_row.append('Охват проф.осмотр')
    new_row.append(year)
    numerator = df_2513[(df_2513['Год'] == year) & (df_2513['Строка'] == 1) & (df_2513['Графа'] == 3)]['Значение'].iloc[0]
    denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['Всего'].iloc[0]
    indicator = numerator*100/denominator
    new_row.append(round(indicator, 2))
    new_row.append(numerator)
    new_row.append(denominator)
    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)

#-----------------
    new_row = []
    # id_7.2 форма 30, табл.2513,   стр.4+5,   гр.3) /    Среднегодовая численность населения Иркутской области  в возрасте 0-14 лет * 100%
    new_row.append('id_7.2')
    new_row.append('Охват иммунодиагностикой детей 0-14 лет (в %)')
    new_row.append('Охват иммунол. 0-14')
    new_row.append(year)
    value_1 = df_2513[(df_2513['Год'] == year) & (df_2513['Строка'] == 4) & (df_2513['Графа'] == 3)]['Значение'].iloc[0]
    value_2 = df_2513[(df_2513['Год'] == year) & (df_2513['Строка'] == 5) & (df_2513['Графа'] == 3)]['Значение'].iloc[0]
    numerator = (
        (value_1 if pd.notnull(value_1) else 0) +
        (value_2 if pd.notnull(value_2) else 0)
    )
    denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['0-14'].iloc[0]
    indicator = numerator*100/denominator
    new_row.append(round(indicator, 2))
    new_row.append(numerator)
    new_row.append(denominator)
    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
#-----------------
    new_row = []
    # id_7.3 форма 30, табл.2513,   стр.2,   гр.3) /    Среднегодовая численность населения Иркутской области  старше 15 лет * 100%
    new_row.append('id_7.3')
    new_row.append('Охват флюорографическими осмотрами населения старше 15 лет (в %)')
    new_row.append('Охват ФЛГ')
    new_row.append(year)
    numerator = (
        df_2513[(df_2513['Год'] == year) & (df_2513['Строка'] == 2) & (df_2513['Графа'] == 3)]['Значение'].iloc[0]
    )
    denominator = df_population[(df_population['Год'] == year) & (df_population['Пол'] == 'всего')]['15+'].iloc[0]
    indicator = numerator*100/denominator
    new_row.append(round(indicator, 2))
    new_row.append(numerator)
    new_row.append(denominator)
    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
#-----------------
    new_row = []
    # id_7.4 форма 30, табл.2513,   стр.2,   гр.5) /     форма 30, табл.2513,   стр.2,   гр.3)  * 1000
    new_row.append('id_7.4')
    new_row.append('Выявляемость туберкулеза методом флюорографии (1000 осмотренных)')
    new_row.append('Выявляемость ФЛГ')
    new_row.append(year)
    value_1 = df_2513[(df_2513['Год'] == year) & (df_2513['Строка'] == 2) & (df_2513['Графа'] == 5)]['Значение'].iloc[0]
    value_2 = df_2513[(df_2513['Год'] == year) & (df_2513['Строка'] == 2) & (df_2513['Графа'] == 3)]['Значение'].iloc[0]
    numerator = (value_1 if pd.notnull(value_1) else 0)
    denominator = (value_2 if pd.notnull(value_1) else 0)
    if denominator != 0:
        indicator = numerator*1000/denominator
    else:
        indicator = 0.0
    new_row.append(round(indicator, 2))
    new_row.append(numerator)
    new_row.append(denominator)
    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)
#------------------------
    new_row = []
    # id_7.5 форма 30, табл.2513,   стр.3,   гр.5) /     форма 30, табл.2513,   стр.3,   гр.3)  * 1000
    new_row.append('id_7.5')
    new_row.append('Выявляемость туберкулеза бактериоскопически (1000 осмотренных)')
    new_row.append('Выявляемость бак')
    new_row.append(year)
    value_1 = df_2513[(df_2513['Год'] == year) & (df_2513['Строка'] == 3) & (df_2513['Графа'] == 5)]['Значение'].iloc[0]
    value_2 = df_2513[(df_2513['Год'] == year) & (df_2513['Строка'] == 3) & (df_2513['Графа'] == 3)]['Значение'].iloc[0]
    numerator = (value_1 if pd.notnull(value_1) else 0)
    denominator = (value_2 if pd.notnull(value_1) else 0)
    if denominator != 0:
        indicator = numerator*1000/denominator
    else:
        indicator = 0.0
    new_row.append(round(indicator, 2))
    new_row.append(numerator)
    new_row.append(denominator)
    data.append(new_row)
    if year <= 2018:
        data_2016_2018.append(new_row)

df_table_7 = pd.DataFrame(data, columns=columns)
df_table_7_2016_2018 = pd.DataFrame(data_2016_2018, columns=columns)
df_table_7

,id,name,short_name,year,indicator,numerator,denominator
0,id_7.1,Охват населения всеми видами осмотров (в %),Охват проф.осмотр,2016,78.49,1892276.0,2410851.0
1,id_7.2,Охват иммунодиагностикой детей 0-14 лет (в %),Охват иммунол. 0-14,2016,93.33,455644.0,488187.0
2,id_7.3,Охват флюорографическими осмотрами населения с...,Охват ФЛГ,2016,73.40,1411232.0,1922664.0
3,id_7.4,Выявляемость туберкулеза методом флюорографии ...,Выявляемость ФЛГ,2016,1.08,1523.0,1411232.0
4,id_7.5,Выявляемость туберкулеза бактериоскопически (1...,Выявляемость бак,2016,3.43,40.0,11666.0
5,id_7.1,Охват населения всеми видами осмотров (в %),Охват проф.осмотр,2017,82.14,1976734.0,2406548.0
6,id_7.2,Охват иммунодиагностикой детей 0-14 лет (в %),Охват иммунол. 0-14,2017,94.89,469021.0,494280.0
7,id_7.3,Охват флюорографическими осмотрами населения с...,Охват ФЛГ,2017,78.66,1504164.0,1912269.0
8,id_7.4,Выявляемость туберкулеза методом флюорографии ...,Выявляемость ФЛГ,2017,0.92,1386.0,1504164.0
9,id_7.5,Выявляемость туберкулеза бактериоскопически (1...,Выявляемость бак,2017,2.82,18.0,6379.0
10,id_7.1,Охват населения всеми видами осмотров (в %),Охват проф.осмотр,2018,81.73,1962309.0,2400979.0
11,id_7.2,Охват иммунодиагностикой детей 0-14 лет (в %),Охват иммунол. 0-14,2018,93.74,466075.0,497183.0
12,id_7.3,Охват флюорографическими осмотрами населения с...,Охват ФЛГ,2018,78.21,1488995.0,1903796.0
13,id_7.4,Выявляемость туберкулеза методом флюорографии ...,Выявляемость ФЛГ,2018,0.81,1204.0,1488995.0
14,id_7.5,Выявляемость туберкулеза бактериоскопически (1...,Выявляемость бак,2018,1.03,7.0,6794.0
15,id_7.1,Охват населения всеми видами осмотров (в %),Охват проф.осмотр,2019,83.44,1998055.0,2394478.0
16,id_7.2,Охват иммунодиагностикой детей 0-14 лет (в %),Охват иммунол. 0-14,2019,95.53,475211.0,497434.0
17,id_7.3,Охват флюорографическими осмотрами населения с...,Охват ФЛГ,2019,80.03,1518209.0,1897045.0
18,id_7.4,Выявляемость туберкулеза методом флюорографии ...,Выявляемость ФЛГ,2019,0.74,1129.0,1518209.0
19,id_7.5,Выявляемость туберкулеза бактериоскопически (1...,Выявляемость бак,2019,2.65,12.0,4525.0
20,id_7.1,Охват населения всеми видами осмотров (в %),Охват проф.осмотр,2020,71.64,1707268.0,2383107.0
21,id_7.2,Охват иммунодиагностикой детей 0-14 лет (в %),Охват иммунол. 0-14,2020,86.21,427473.0,495875.0
22,id_7.3,Охват флюорографическими осмотрами населения с...,Охват ФЛГ,2020,67.61,1276013.0,1887233.0
23,id_7.4,Выявляемость туберкулеза методом флюорографии ...,Выявляемость ФЛГ,2020,0.65,829.0,1276013.0
24,id_7.5,Выявляемость туберкулеза бактериоскопически (1...,Выявляемость бак,2020,11.66,44.0,3773.0
25,id_7.1,Охват населения всеми видами осмотров (в %),Охват проф.осмотр,2021,78.07,1849615.0,2369234.0
26,id_7.2,Охват иммунодиагностикой детей 0-14 лет (в %),Охват иммунол. 0-14,2021,92.12,448648.0,487016.0
27,id_7.3,Охват флюорографическими осмотрами населения с...,Охват ФЛГ,2021,73.91,1391224.0,1882219.0
28,id_7.4,Выявляемость туберкулеза методом флюорографии ...,Выявляемость ФЛГ,2021,0.55,772.0,1391224.0
29,id_7.5,Выявляемость туберкулеза бактериоскопически (1...,Выявляемость бак,2021,8.07,29.0,3593.0
30,id_7.1,Охват населения всеми видами осмотров (в %),Охват проф.осмотр,2022,80.52,1895343.0,2353904.0
31,id_7.2,Охват иммунодиагностикой детей 0-14 лет (в %),Охват иммунол. 0-14,2022,95.01,456722.0,480722.0
32,id_7.3,Охват флюорографическими осмотрами населения с...,Охват ФЛГ,2022,76.41,1431385.0,1873182.0
33,id_7.4,Выявляемость туберкулеза методом флюорографии ...,Выявляемость ФЛГ,2022,0.54,766.0,1431385.0
34,id_7.5,Выявляемость туберкулеза бактериоскопически (1...,Выявляемость бак,2022,10.24,41.0,4005.0
35,id_7.1,Охват населения всеми видами осмотров (в %),Охват проф.осмотр,2023,81.72,1910125.0,2337449.0
36,id_7.2,Охват иммунодиагностикой детей 0-14 лет (в %),Охват иммунол. 0-14,2023,96.22,458605.0,476624.0
37,id_7.3,Охват флюорографическими осмотрами населения с...,Охват ФЛГ,2023,77.65,1444938.0,1860825.0
38,id_7.4,Выявляемость туберкулеза методом флюорографии ...,Выявляемость ФЛГ,2023,0.52,745.0,1444938.0
39,id_7.5,Выявляемость туберкулеза бактериоскопически (1...,Выявляемость бак,2023,5.52,19.0,3441.0
40,id_7.1,Охват населения всеми видами осмотров (в %),Охват проф.осмотр,2024,84.95,1979761.0,2330537.0
41,id_7.2,Охват иммунодиагностикой детей 0-14 лет (в %),Охват иммунол. 0-14,2024,98.03,461566.0,470864.0
42,id_7.3,Охват флюорографическими осмотрами населения с...,Охват ФЛГ,2024,81.58,1517149.0,1859673.0
43,id_7.4,Выявляемость туберкулеза методом флюорографии ...,Выявляемость ФЛГ,2024,0.46,699.0,1517149.0
44,id_7.5,Выявляемость туберкулеза бактериоскопически (1...,Выявляемость бак,2024,12.08,33.0,2731.0

In [8]:
df_table_7_2016_2018.to_csv(f'{path}Common_2016-2018/table_7_2016-2018.csv', index=False)
df_table_7.to_csv(f'{path}Common/table_7_2016-2024.csv', index=False)